### PR TITLE
ci: enable GCS+gRPC production integration tests

### LINKED ISSUE #7257: Restore integration tests disabled for GCS+gRPC
There is a small number of bugs in the (pre-release not GA) GCS+gRPC service, specially with the v2/ protos. I have disabled the tests that fail, this is a bug to reference from the TODO entries.

### PR DESCRIPTION
**Pull request by coryan**
The integration tests against production were disabled while the protos
stabilized. There are no anticipated breaking changes at this point.

We cannot pass the options created for a `GrpcClient` to a `CurlClient`.
The latter has a very subtle interpretation of `AuthorityOption` as it
supports two separate services: `iamcredentials.googleapis.com` is
used to sign blobs.

A number of tests remain disabled because they use metadata operations
in gRPC, which are not ready in production. Changed their TODO entries
to point to the right bug.

Fixes #7257

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9060)

### CODE REVIEW

File: google/cloud/storage/grpc_plugin.cc [hunk 1]
```diff
@@ -15,19 +15,23 @@
...
-  auto config = opts.get<GrpcPluginOption>();
+  using ::google::cloud::internal::GetEnv;
+  auto const config = GetEnv("GOOGLE_CLOUD_CPP_STORAGE_GRPC_CONFIG")
+                          .value_or(opts.get<GrpcPluginOption>());
   if (config == "none" || config.empty()) {
     return google::cloud::storage::Client(std::move(opts));
   }
   if (config == "metadata") {
+    opts =
+        google::cloud::storage::internal::DefaultOptionsGrpc(std::move(opts));
```
Comment (dbolduc) [inline google/cloud/storage/grpc_plugin.cc:34]: I am confused. Is the point that we do not want to `DefaultOptionsGrpc` if `config == "media"` ? I would have guessed that `HybridClient` wants the options defaulted.

Also, pulling the env var stuff out of `DefaultOptionsGrpc()` means we have no test that the env var overrides the `GrpcPluginOption`... that seems less good to me.

File: google/cloud/storage/internal/grpc_client_test.cc [hunk 2]
```diff
@@ -182,24 +179,6 @@ std::shared_ptr<GrpcClient> CreateTestClient(
   return GrpcClient::CreateMock(std::move(stub), TestOptions());
 }
 
-TEST_F(GrpcClientTest, DefaultOptionsGrpcNoEnv) {
```
Comment (dbolduc) [inline google/cloud/storage/internal/grpc_client_test.cc:185]: :/

File: google/cloud/storage/grpc_plugin.cc (hunk 1 above)
Comment (dbolduc) [reply google/cloud/storage/grpc_plugin.cc:34]: Sorry, I just read the PR description. You explained the point.

It would still be nice if we could unit test the env var behavior. Can we default the authority option differently within `DefaultOptionsGrpc()` depending on the config?

Comment (coryan) [reply google/cloud/storage/grpc_plugin.cc:34]: > Sorry, I just read the PR description. You explained the point.
> 
> It would still be nice if we could unit test the env var behavior. Can we default the authority option differently within `DefaultOptionsGrpc()` depending on the config?

That would spread the knowledge of what `GrpcPluginOption` does across multiple files.  Does not seem very desirable.  I created a new unit test for the `DefaultGrpcClient()` function.

File: google/cloud/storage/grpc_plugin_test.cc [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+using ::google::cloud::storage::internal::GrpcClient;
+using ::google::cloud::storage::internal::HybridClient;
+using ::google::cloud::storage::internal::RetryClient;
+using ::google::cloud::testing_util::ScopedEnvironment;
+using ::testing::IsNull;
+using ::testing::NotNull;
+
+TEST(GrpcPluginTest, MetadataConfigCreatesGrpc) {
+  // Disable the RestClient, while this is not the default, it is enabled in
+  // some of our CI builds.
```
Comment (dbolduc) [inline google/cloud/storage/grpc_plugin_test.cc:40]: maybe: `// Explicitly disable the RestClient, which may be enabled by our CI builds.` here and elsewhere

File: google/cloud/storage/grpc_plugin_test.cc [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+  auto rest = ScopedEnvironment("GOOGLE_CLOUD_CPP_STORAGE_HAVE_REST_CLIENT",
+                                absl::nullopt);
+  // Disable logging, also enabled in most of our CI builds
```
Comment (dbolduc) [inline google/cloud/storage/grpc_plugin_test.cc:43]: `// Explicitly disable logging, which may be enabled by our CI builds.`

**Review by dbolduc — APPROVED** [review]
That works. some nits about the comments
