### PR TITLE
fix: CompletionQueue::RunAsync is always async

### LINKED ISSUE #4083: Potential deadlocks in bigtable::MutationBatcher
**Does this issue affect the google-cloud-cpp project?**

Yes.

**What component of `google-cloud-cpp` is this related to?**

Bigtable

**Describe the bug**

This code is suspect:

https://github.com/googleapis/google-cloud-cpp/blob/a68f42a33dca00c35818ccbfbbe3bec96bc7dd0e/google/cloud/bigtable/mutation_batcher.cc#L185-L189

It calls `TryAdmin()` which performs a lot of work, potentially making RPCs:

https://github.com/googleapis/google-cloud-cpp/blob/a68f42a33dca00c35818ccbfbbe3bec96bc7dd0e/google/cloud/bigtable/mutation_batcher.cc#L192-L207

This can deadlock and/or make no progress.

**To Reproduce**

This is a report from a customer, in their application they need to run about a thousand processes for the deadlock to happen.

**Expected behavior**

The `MutationBatcher` should guarantee progress.

**Operating system:**

Linux, no further details available.

### PR DESCRIPTION
**Pull request by coryan**
Prior to this change we sometimes ran the callable passed to
`CompletionQueue::RunAsync()` in the calling thread and not
in the thread pool, which was hard to reason about.

As part of these changes I also fixed the code to support
move-only callables, and added a test for it.

The code is "future proofed" to support a `void()` callable.
Which is interesting for a number of reasons (think "executors").

Fixes #4083 

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4448)

### CODE REVIEW

File: google/cloud/completion_queue.cc [hunk 1]
```diff
@@ -76,6 +76,38 @@ class AsyncTimerFuture : public internal::AsyncGrpcOperation {
...
+ private:
+  bool Notify(bool) override {
+    fun_->exec();
+    fun_.reset();
+    return true;
+  }
+
+  std::shared_ptr<internal::CompletionQueueImpl> cq_;
+  std::unique_ptr<internal::RunAsyncBase> fun_;
+  // Holds the underlying handle, it might be a nullpotr in tests.
```
Comment (devbww) [inline google/cloud/completion_queue.cc:107]: s/nullpotr/nullptr/

Comment (coryan) [reply google/cloud/completion_queue.cc]: Fixed, thanks.
