### PR TITLE
fix(pubsub): sometimes published oversized batches

### LINKED ISSUE #5408: Publish batches can exceed the byte size limits
After some layers of indirection `Publisher::Publish()`  is implemented by:

https://github.com/googleapis/google-cloud-cpp/blob/9eff7232c7a9dcf5ad3bd41d29b9d42b84f202d0/google/cloud/pubsub/internal/batching_publisher_connection.cc#L69

Which first adds a message:

https://github.com/googleapis/google-cloud-cpp/blob/9eff7232c7a9dcf5ad3bd41d29b9d42b84f202d0/google/cloud/pubsub/internal/batching_publisher_connection.cc#L97

and then verifies if the batch must be flushed:

https://github.com/googleapis/google-cloud-cpp/blob/9eff7232c7a9dcf5ad3bd41d29b9d42b84f202d0/google/cloud/pubsub/internal/batching_publisher_connection.cc#L100

This does not work correctly when sending large messages.  The previous batched messages may be too small, but adding the message may create a batch over the limit. Most of the time this does not matter.  However, Pub/Sub has a hard limit of 10MiB. If the batch setting is something like 9.5MiB, and the new message is about 1MiB this can create a problem.

We need to check if the message fits in the batch *first*, if it does not we should first flush the batch, and only then add it.

There are some complications (aren't there always), we release the lock to flush a batch, so we may get other messages in between.  And the message itself may be too large, in which case we should send it on its own (and let the server validate the size).

### PR DESCRIPTION
**Pull request by coryan**
`pubsub_internal::BatchingPublisherConnection` failed to flush before
accepting a message that would exceed the total bytes limit.

Fixes #5408

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5409)

### CODE REVIEW

File: google/cloud/pubsub/internal/batching_publisher_connection.cc [hunk 1]
```diff
@@ -178,6 +176,22 @@ void BatchingPublisherConnection::OnTimer() {
...
+    promise<StatusOr<std::string>> p;
+    Status status;
+    void operator()() { p.set_value(std::move(status)); }
+  };
+  cq_.RunAsync(MoveCapture{std::move(p), corked_status_});
+
+  return f;
+}
+
+void Fits(std::unique_lock<std::mutex> const& lk, std::size_t bytes);
```
Comment (devbww) [inline google/cloud/pubsub/internal/batching_publisher_connection.cc:193]: Remnant of something?

Comment (coryan) [reply google/cloud/pubsub/internal/batching_publisher_connection.cc]: Yes, thanks!  I am surprised the compiler(s) did not catch that, thanks for pointing it out.

**Review by devbww — APPROVED** [review]
