### PR TITLE
fix(GCS+gRPC): race condition in async `Insert()`

### LINKED ISSUE #12710: flake: coverage-ci build failing due to "no valid records found in tracefile"
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/35e970cc2dbff24bf3d66dd669a345529cae7031/fedora-37-bazel-coverage/log-e7772137-123e-4b21-acc1-0cabeb38af1e.txt

`lcov: ERROR: no valid records found in tracefile /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-grpc-media/test_attempts/coverage.dat`

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0cba02571f84c25a3ed0ab9f1fc8511e542b5045/fedora-37-bazel-coverage/log-9aa56942-8465-4053-b1d4-b0ea99fde929.txt

`lcov: ERROR: no valid records found in tracefile /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-default/test_attempts/coverage.dat`

### PR DESCRIPTION
**Pull request by coryan**
The code assumed the `OnWrite()` callback (and the follow-on `Write()` call) would be invoked after it had a chance to prepare for the `Write()` call.  Clever in that overlapped some I/O with CPU operations, but wrong in that scheduling does not work like this.

I also changed the test to make the errors easier to interpret.

Fixes #12710

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/12715)

### CODE REVIEW

File: google/cloud/storage/tests/async_client_integration_test.cc [hunk 1]
```diff
@@ -156,7 +168,14 @@ TEST_F(AsyncClientIntegrationTest, StreamingRead) {
     std::tie(payload, token) = *std::move(p);
     for (auto v : payload.contents()) actual += std::string(v);
   }
-  EXPECT_EQ(actual, expected_data);
+  EXPECT_EQ(actual.size(), expected_size);
+  auto view = absl::string_view(actual);
+  for (auto const& expected : insert_data) {
+    ASSERT_GE(view.size(), expected.size());
+    ASSERT_EQ(expected, view.substr(0, expected.size()));
+    view = view.substr(expected.size());
```
Comment (devbww) [inline google/cloud/storage/tests/async_client_integration_test.cc:176]: Opt: Consider `view.remove_prefix(expected.size())`.

File: google/cloud/storage/tests/async_client_integration_test.cc [hunk 2]
```diff
@@ -156,7 +168,14 @@ TEST_F(AsyncClientIntegrationTest, StreamingRead) {
...
+  }
+  ASSERT_EQ(view, absl::string_view{});
```
Comment (devbww) [inline google/cloud/storage/tests/async_client_integration_test.cc:178]: s/ASSERT/EXPECT/?

File: google/cloud/storage/tests/async_client_integration_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/tests/async_client_integration_test.cc]: Done.

File: google/cloud/storage/tests/async_client_integration_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/tests/async_client_integration_test.cc]: Done.
