### PR TITLE
LockBucketRetentionPolicy returns a BucketMetadata.

### LINKED ISSUE #1859: Storage Bucket Lock LockRetentionPolicy is missing response bucket resource
The GCS API [reference documentation for LockRetentionPolicy](https://cloud.google.com/storage/docs/json_api/v1/buckets/lockRetentionPolicy) was incorrect. The operation does return a bucket resource.

This bug request is to support bucket resource returned from this operation. 

Per: #1853

### PR DESCRIPTION
**Pull request by coryan**
This fixes #1859.  The return type for `LockBucketRetentionPolicy()` should be
`StatusOr<BucketMetadata>`, the documentation for the JSON API used to be
wrong and we implemented based on the old docs.

### CODE REVIEW

File: google/cloud/storage/examples/storage_bucket_samples.cc [hunk 1]
```diff
@@ -936,14 +936,17 @@ void LockRetentionPolicy(google::cloud::storage::Client client, int& argc,
...
-    if (!status.ok()) {
+    if (!updated.ok()) {
       std::cerr << "Error locking bucket retention policy for bucket "
-                << bucket_name << ", status=" << status.status() << std::endl;
+                << bucket_name << ", status=" << updated.status() << std::endl;
     }
+
     std::cout << "Retention policy successfully locked for bucket "
-              << bucket_name << std::endl;
+              << updated->name() << "\nFull metadata: " << *updated
```
Comment (frankyn) [inline google/cloud/storage/examples/storage_bucket_samples.cc]: Add the `retentionPolicy.effectiveTime` to the output so it's not lost in the full metadata.

File: google/cloud/storage/examples/storage_bucket_samples.cc [hunk 2]
```diff
@@ -936,14 +936,17 @@ void LockRetentionPolicy(google::cloud::storage::Client client, int& argc,
                 << ", status=" << original.status() << std::endl;
       return;
     }
-    StatusOr<void> status = client.LockBucketRetentionPolicy(
+
+    StatusOr<gcs::BucketMetadata> updated = client.LockBucketRetentionPolicy(
         bucket_name, original->metageneration());
-    if (!status.ok()) {
+    if (!updated.ok()) {
```
Comment (frankyn) [inline google/cloud/storage/examples/storage_bucket_samples.cc]: Add a new line before this one to separate the `LockBucketRetentionPolicy()` request and `if (!updated.ok()) {`.

Comment (frankyn) [reply google/cloud/storage/examples/storage_bucket_samples.cc]: Whoops, missed one, `updated` to `updated_metadata` or `updated_meta` if you want to keep the that separate.

File: google/cloud/storage/examples/storage_bucket_samples.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/examples/storage_bucket_samples.cc]: That is a `std::chrono::time_point`, and, AFAIK, there is no formatting of those until C++20.  We have a formatting function in `google::cloud::storage::internal`, but really should not be using it in the examples.  I printed the retention policy in full, which is shorter than the full metadata anyway.

File: google/cloud/storage/examples/storage_bucket_samples.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/examples/storage_bucket_samples.cc]: Added the newline, thanks.

I changed the variable name, but I disagree.  What else could it be given the variable type (which is right there, a couple of lines before)?  I cannot be a `updated_int` or `updated_string`, or `updated_object_metadata`.  The type is `StatusOr<BucketMetadata>` it *must* be a status or a bucket metadata, nothing else will do.

File: google/cloud/storage/examples/storage_bucket_samples.cc (hunk 1 above)
Comment (frankyn) [reply google/cloud/storage/examples/storage_bucket_samples.cc]: I wonder if users will find it helpful to have a helper method that converts time_point to a human readable format, then again they can output all the metadata. 

I'll defer to community feedback on this case. Thanks for clarifying.

Comment (devbww) [reply google/cloud/storage/examples/storage_bucket_samples.cc]: If/when Abseil becomes a dependency we might consider using absl::Time instead of std::chrono::time_point, at which point this all gets much easier.

File: google/cloud/storage/examples/storage_bucket_samples.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/examples/storage_bucket_samples.cc]: Done.

**Comment by devbww** [comment]
Aside: Given that this removes one instance of StatusOr<void>, I'm waiting for the merge before sending out the StatusOr<void> -> Status PR.

**Comment by coryan** [comment]
@devbww this is now merged, you can push your `StatusOr<void>` :arrow_right:  `Status` PR at will.
