### PR TITLE
fix(storage): better error code for CreateBucket() and 409 errors

### LINKED ISSUE #10478: Calling storage::Client::CreateBucket() returns kAborted instead of kAlreadyExists for existing bucket
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
google/cloud/storage

**Describe the bug**
Calling storage::Client::CreateBucket() for an already existing bucket returns ::StatusCode::kAborted with a message:
"Permanent error CreateBucket: Your previous request to create the named bucket succeeded and you already own it."

The expectation for the method is to return ::StatusCode::kAlreadyExists.

**To Reproduce**

1. Call function storage::Client::CreateBucket({bucket_name},...) and ensure that it succeeds.
2. Call the same function again with the same bucket name.

Returned value of google:: cloud ::Status with:
code: kAborted
message: "Permanent error CreateBucket: Your previous request to create the named bucket succeeded and you already own it."

**Expected behavior**
Expected return value:
google:: cloud ::Status with code=kAlreadyExists.

**Operating system:**
ubuntu 20.04 LTS

**What compiler and version are you using?**
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.1.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --disable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-2V7zgg/gcc-11-11.1.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-2V7zgg/gcc-11-11.1.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (Ubuntu 11.1.0-1ubuntu1~20.04)

**What version of `google-cloud-cpp` are you using?**
v2.4.0

### PR DESCRIPTION
**Pull request by coryan**
It seems that 409 should be treated as a `kAlreadyExists` in this case, and this case only.

Fixes #10478

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10480)

### CODE REVIEW

**Review by dbolduc — APPROVED** [review]

File: google/cloud/storage/internal/curl_client.cc [hunk 1]
```diff
@@ -204,13 +204,20 @@ StatusOr<BucketMetadata> CurlClient::CreateBucket(
...
-  return CheckedFromString<BucketMetadataParser>(
+  auto response = CheckedFromString<BucketMetadataParser>(
       std::move(builder).BuildRequest().MakeRequest(request.json_payload()));
+  // GCS returns a 409 when buckets already exist:
+  //     https://cloud.google.com/storage/docs/json_api/v1/status-codes#409-conflict
+  // This seems to be the only case where kAlreadyExists is a better match
+  // for 409 than kAborted.
+  if (!response && response.status().code() == StatusCode::kAborted) {
+    return google::cloud::internal::WithStatusCode(std::move(response).status(),
+                                                   StatusCode::kAlreadyExists);
```
Comment (devbww) [inline google/cloud/storage/internal/curl_client.cc:218]: Q. Could we, almost as effectively, avoid the extra `Status` complications with just ...
```
    return Status(StatusCode::kAlreadyExists, response.status().message(),
                  response.status().error_info());
```

Comment (coryan) [reply google/cloud/storage/internal/curl_client.cc]: I wanted to avoid the extra copies, but meh.  This is not happening on each call or anything.
