### PR TITLE
test(storage): deflake benchmark integration test

### LINKED ISSUE #6893: [Flake] Error in smoke test for storage benchmarks
During cleanup the benchmark smoke tests delete some objects. It seems that these deletes can be retried. At least once the first attempt succeeded but the connection was closed, and then the second attempt failed with `kNotFound`.

We probably should ignore errors during the cleanup phase.

```
2021-06-29T20:08:26.994341200Z [INFO] <2812> DeleteObject() >> status={{

  "error": {

    "code": 504,

    "message": "",

    "errors": [

      {

        "message": "",

        "domain": "global",

        "reason": "gatewayTimeout"

      }

    ]

  }

}

 [INTERNAL]} (google/cloud/storage/internal/logging_client.cc:51)

2021-06-29T20:08:28.601229900Z [INFO] <2812> DeleteObject() << DeleteObjectRequest={bucket_name=cloud-cpp-testing-bucket, object_name=ob-2kfDlUhnFdpZNC6iWe8aL8MKQD9xKXHvJHb1ttQ7l5egE6Z9wuvXR7ITeeFgID5HSQTIAMWeWQaBnHWVLTadEE44B6MJVvxn7luFiiDPOvCiKRKKBgIKWjMuqd9pFwZt.txt} (google/cloud/storage/internal/logging_client.cc:46)

2021-06-29T20:08:28.654523600Z [INFO] <2812> DeleteObject() >> status={{

  "error": {

    "code": 404,

    "message": "No such object: cloud-cpp-testing-bucket/ob-2kfDlUhnFdpZNC6iWe8aL8MKQD9xKXHvJHb1ttQ7l5egE6Z9wuvXR7ITeeFgID5HSQTIAMWeWQaBnHWVLTadEE44B6MJVvxn7luFiiDPOvCiKRKKBgIKWjMuqd9pFwZt.txt",

    "errors": [

      {

        "message": "No such object: cloud-cpp-testing-bucket/ob-2kfDlUhnFdpZNC6iWe8aL8MKQD9xKXHvJHb1ttQ7l5egE6Z9wuvXR7ITeeFgID5HSQTIAMWeWQaBnHWVLTadEE44B6MJVvxn7luFiiDPOvCiKRKKBgIKWjMuqd9pFwZt.txt",

        "domain": "global",

        "reason": "notFound"

      }

    ]

  }

}

 [NOT_FOUND]} (google/cloud/storage/internal/logging_client.cc:51)
```

### PR DESCRIPTION
**Pull request by coryan**
Fixes #6893

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6898)

### CODE REVIEW

File: google/cloud/storage/benchmarks/throughput_experiment_test.cc [hunk 1]
```diff
@@ -64,11 +64,9 @@ TEST_P(ThroughputExperimentIntegrationTest, Upload) {
...
                                       /*enable_md5=*/false};
     auto result = e->Run(bucket_name_, object_name, config);
-    EXPECT_STATUS_OK(result.status);
-    if (result.status.ok()) {
-      auto status = client->DeleteObject(bucket_name_, object_name);
-      EXPECT_STATUS_OK(status);
-    }
+    ASSERT_STATUS_OK(result.status);
+    // This is not checked as it is just for cleanup.
+    (void)client->DeleteObject(bucket_name_, object_name);
```
Comment (devbww) [inline google/cloud/storage/benchmarks/throughput_experiment_test.cc:69]: Q.  Would it be "nicer" to go back to the original formulation, but allow either OK or NOT_FOUND from the `DeleteObject()`?

Comment (coryan) [reply google/cloud/storage/benchmarks/throughput_experiment_test.cc]: I am happy either way, and we can always change it. Done.

**Review by devbww — APPROVED** [review]
