### PR TITLE
fix(common): deflake timer_queue_test

### LINKED ISSUE #10524: TimerQueueTest.ScheduleMultipleRunners ids.size() expectation failure
```
Step #3: [ RUN      ] TimerQueueTest.ScheduleMultipleRunners
Step #3: google/cloud/internal/timer_queue_test.cc:109: Failure
Step #3: Expected: (ids.size()) > (1), actual: 1 vs 1
Step #3: [  FAILED  ] TimerQueueTest.ScheduleMultipleRunners (1001 ms)
```
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/915c1dc9-4e17-438d-97db-ddb53e14401b;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/8a7baaf24568243caa35b040c236aff93a464fc3/fedora-36-bazel-ubsan/log-915c1dc9-4e17-438d-97db-ddb53e14401b.txt

### PR DESCRIPTION
**Pull request by coryan**
Fixes #10524

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10525)

### CODE REVIEW

File: google/cloud/internal/timer_queue_test.cc [hunk 1]
```diff
@@ -88,7 +88,8 @@ TEST(TimerQueueTest, ScheduleMultipleRunners) {
   std::vector<future<std::thread::id>> futures(kTimers);
   auto const now = std::chrono::system_clock::now();
   std::generate(futures.begin(), futures.end(), [&, now] {
-    return tq.Schedule(now + std::chrono::seconds(1)).then([](auto) {
+    return tq.Schedule(now).then([](auto) {
+      std::this_thread::sleep_for(std::chrono::milliseconds(1));
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:92]: While I'm sure this helps, it stills seems like there is no guarantee that a single thread doesn't yield all values.

**Review by devbww — APPROVED** [review]

File: google/cloud/internal/timer_queue_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc:92]: Agree.  But the probability seems to be less than 1 in 10,000 😐
