### PR TITLE
fix: race condition canceling CompletionQueue timers

### LINKED ISSUE #5141: Weird tsan flake
While testing an updated version of Absei (not a release, just using Abseil's HEAD) in draft PR https://github.com/googleapis/google-cloud-cpp/pull/5130, our tsan build failed with a strange stack trace. After a re-run everything passed. The stack trace doesn't really include much Abseil code, so it doesn't _look_ like an Abseil bug, but I'm not sure. 

Failed log: https://source.cloud.google.com/results/invocations/91181182-5c03-4ed0-b81d-9709b2af3526/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Ftsan-presubmit/log

```
SUMMARY: ThreadSanitizer: data race /proc/self/cwd/google/cloud/pubsub/samples/samples.cc:1180:13 in (anonymous namespace)::SubscriberRetrySettings(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)::$_2::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const::'lambda'(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler)::operator()(google::cloud::pubsub::v1::Message const&, google::cloud::pubsub::v1::AckHandler) const
```

I tried about 20x to reproduce this on my local machine. I succeeded in reproducing a tsan error on my local  machine one time, and the stack trace had nothing to do w/ pubsub (as the one in the log above does). Here's the tsan error from my local machine.
[local-tsan-error.txt](https://github.com/googleapis/google-cloud-cpp/files/5272124/local-tsan-error.txt)

```
SUMMARY: ThreadSanitizer: data race /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/unique_ptr.h:291:6 in std::unique_ptr<grpc_impl::Alarm, std::default_delete<grpc_impl::Alarm> >::~unique_ptr() 
```

I now seem to be unable to reproduce the problem again.

### PR DESCRIPTION
**Pull request by coryan**
Fixes #5141

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5176)

### CODE REVIEW

File: google/cloud/completion_queue_test.cc [hunk 1]
```diff
@@ -75,6 +75,36 @@ class MockOperation : public internal::AsyncGrpcOperation {
   MOCK_METHOD1(Notify, bool(bool));
 };
 
+/// @test A regression test for #5141
+TEST(CompletionQueueTest, TimerCancel) {
+  // There are a lot of magical numbers in this test, on my workstation I was
+  // able to reproduce #5141 99 out of 100 times on my workstation.
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:81]: "... on my workstation ... on my workstation" repetition?

File: google/cloud/completion_queue_test.cc [hunk 2]
```diff
@@ -75,6 +75,36 @@ class MockOperation : public internal::AsyncGrpcOperation {
   MOCK_METHOD1(Notify, bool(bool));
 };
 
+/// @test A regression test for #5141
+TEST(CompletionQueueTest, TimerCancel) {
+  // There are a lot of magical numbers in this test, on my workstation I was
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:80]: s/, on/, but on/?

File: google/cloud/internal/default_completion_queue_impl.cc [hunk 3]
```diff
@@ -48,42 +48,45 @@ namespace {
...
-
-  future<StatusOr<std::chrono::system_clock::time_point>> GetFuture() {
-    return promise_.get_future();
+  using ValueType = StatusOr<std::chrono::system_clock::time_point>;
+
+  // We need to create the shared_ptr before completing the initialization, so
+  // use a factory member function.
+  static std::pair<std::shared_ptr<AsyncTimerFuture>, future<ValueType>>
+  Create() {
+    auto self = std::shared_ptr<AsyncTimerFuture>(new AsyncTimerFuture);
```
Comment (devbww) [inline google/cloud/internal/default_completion_queue_impl.cc:57]: `std::make_shared()`?

File: google/cloud/internal/default_completion_queue_impl.cc [hunk 4]
```diff
@@ -48,42 +48,45 @@ namespace {
...
+    auto weak = std::weak_ptr<AsyncTimerFuture>(self);
+    self->promise_ = promise<AsyncTimerFuture::ValueType>([weak] {
+      if (auto self = weak.lock()) self->Cancel();
+    });
+    return {self, self->promise_.get_future()};
   }
 
+  void SetPromise(promise<ValueType> p) { promise_ = std::move(p); }
```
Comment (devbww) [inline google/cloud/internal/default_completion_queue_impl.cc:65]: Unused?

Comment (coryan) [reply google/cloud/internal/default_completion_queue_impl.cc]: Ooops, fixed.

File: google/cloud/internal/default_completion_queue_impl.cc (hunk 3 above)
Comment (coryan) [reply google/cloud/internal/default_completion_queue_impl.cc:57]: I do not think I can, the constructor is private (because the initialization is messy).

File: google/cloud/completion_queue_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/completion_queue_test.cc]: PTAL.

File: google/cloud/completion_queue_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/completion_queue_test.cc]: Fixed.

Comment (devbww) [reply google/cloud/completion_queue_test.cc]: Still sounds a little strange, but I'll leave it to you to decide.

**Review by devbww — APPROVED** [review]
