### PR TITLE
Fix a race condition in MutationBatcher.

### LINKED ISSUE #2140: Integration test for gcs2cbt is crashing.
The `gcs2cbt` integration test is crashing.  Apparently only when given invalid arguments, when it is supposed to print an error message and exit with error.  The test is not sensitive enough to detect that the program terminated with a crash instead.

```
Running integration tests for google/cloud
[ -------- ] gcs2cbt test environment
[ -------- ] Integration test environment set-up
Launching testbench emulator in the background
Successfully connected to testbench [3537]
[ ======== ] Integration test environment set-up.
Launching Cloud Bigtable emulators in the background
Successfully connected to the Cloud Bigtable emulator on localhost:37289.
Successfully connected to the Cloud Bigtable emulator on localhost:45967.
[ RUN      ]  table_admin_snippets create-table running
[       OK ]  table_admin_snippets create-table
[ RUN      ]  storage_bucket_samples create-bucket-for-project running
[       OK ]  storage_bucket_samples create-bucket-for-project
[ RUN      ]  storage_object_samples upload-file running
[       OK ]  storage_object_samples upload-file
[ RUN      ]  gcs2cbt --key=1 running
/v/ci/define-example-runner.sh: line 42:  3624 Aborted                 (core dumped) ${program_path} ${example} ${arguments} >> "${log}" 2>&1 < /dev/null
[    ERROR ]  gcs2cbt --key=1

================ [begin run_example.bxRpuC] ================
./gcs2cbt --key=1 --separator=, fake-project-1551734192-22945 in-1551734192-32324 csv-table-22744 fam fake-bucket-1551734192-19182 contents.csv
Starting 5 workers ... DONE
# HEADER RowId,Header1,Header2,Header3
Reading input file  DONE
Waiting for worker threads E0304 21:16:33.349177889    3632 call.cc:1853]               assertion failed: grpc_cq_begin_op(call->cq, notify_tag)
================ [end run_example.bxRpuC] ================
[ RUN      ]  gcs2cbt running
[       OK ]  gcs2cbt
Killing Bigtable Emulators [3550 3564] .+..+. done.
[ -------- ] Integration test environment tear-down.
Killing testbench server [3537] ... done.
[ ======== ] Integration test environment tear-down.

```

### PR DESCRIPTION
**Pull request by dopiera**
This fixes #2140.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2465)

### CODE REVIEW

File: google/cloud/bigtable/mutation_batcher.cc [hunk 1]
```diff
@@ -250,7 +250,12 @@ void MutationBatcher::SatisfyPromises(
     std::vector<AdmissionPromise> admission_promises,
     std::unique_lock<std::mutex>& lk) {
   std::vector<NoMorePendingPromise> no_more_pending_promises;
-  if (num_requests_pending_ == 0) {
+  if (num_requests_pending_ == 0 && num_outstanding_batches_ == 0) {
+    // We should wait not only on num_requests_pending_ being zero but alson on
+    // num_outstanding_batches_ because we want to allow the user to kill the
+    // completion queue after this promise is fulfilled. Otherwise, the user can
+    // destroy the completion queue while the last batch is still being
+    // processed - we've had this bug.
```
Comment (coryan) [inline google/cloud/bigtable/mutation_batcher.cc]: Maybe link the actual bug number?
