### PR TITLE
fix(pubsub): race condition capturing batching timer

### LINKED ISSUE #9995: pubsub publisher tsan data race flake
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/58ff079d-c9b0-4786-b446-50e68398a937;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/3942b25db6d47c8d421aa827ff54d28fd5229eb9/fedora-36-tsan/log-58ff079d-c9b0-4786-b446-50e68398a937.txt

```
[ RUN      ] BatchingPublisherConnectionTest.BatchTorture
==================
WARNING: ThreadSanitizer: data race (pid=12)
```

I can reliably get this to flake by running the following at HEAD:
```sh
bazel test --test_filter=BatchingPublisherConnectionTest.BatchTorture --config=tsan --runs_per_test=50 --nocache_test_results //google/cloud/pubsub:internal_batching_publisher_connection_test
```

It does not flake before #9991

### PR DESCRIPTION
**Pull request by coryan**
Fixes #9995  Tested with:

```
CXX=clang++ CC=clang bazel test --test_filter=BatchingPublisherConnectionTest.BatchTorture --config=tsan --runs_per_test=10000 //google/cloud/pubsub:internal_batching_publisher_connection_test
INFO: Analyzed target //google/cloud/pubsub:internal_batching_publisher_connection_test (0 packages loaded, 137 targets configured).
INFO: Found 1 test target...
Target //google/cloud/pubsub:internal_batching_publisher_connection_test up-to-date:
  /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/f1b649d8eddab70da217bfe95503f270/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/bin/google/cloud/pubsub/internal_batching_publisher_connection_test
INFO: Elapsed time: 290.361s, Critical Path: 10.31s
INFO: 10001 processes: 1 internal, 10000 linux-sandbox.
INFO: Build completed successfully, 10001 total actions
//google/cloud/pubsub:internal_batching_publisher_connection_test        PASSED in 5.3s
  Stats over 10000 runs: max = 5.3s, min = 0.4s, avg = 1.8s, dev = 0.6s
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9996)

### CODE REVIEW

File: google/cloud/pubsub/internal/batching_publisher_connection.cc [hunk 1]
```diff
@@ -149,16 +149,19 @@ void BatchingPublisherConnection::MaybeFlush(std::unique_lock<std::mutex> lk) {
   // `weak_from_this()`.
   auto weak = std::weak_ptr<BatchingPublisherConnection>(shared_from_this());
   // Note that at this point the lock is released, so whether the timer
-  // schedules later on schedules in this thread has no effect.  In addition,
-  // the assignment to `timer_` is safe.  It is only used from the destructor,
-  // and if the destructor and this function are running at the same time, then
-  // we had a massive problem already.
-  timer_ =
+  // schedules later on schedules in this thread has no effect.
```
Comment (dbolduc) [inline google/cloud/pubsub/internal/batching_publisher_connection.cc:152]: nit: s/later on/later or/

**Review by dbolduc — APPROVED** [review]

File: google/cloud/pubsub/internal/batching_publisher_connection.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/pubsub/internal/batching_publisher_connection.cc]: Done.
