### PR TITLE
ci: deflake googleapis downloads from GitHub

### LINKED ISSUE #8102: Build failed to fetch googleapis data from github
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/d82e4697-5b63-4e69-8590-66aedae4c47f;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/56601817f1c8a853436c10c30360e0c75c51f94d/fedora-34-cmake-install/log-d82e4697-5b63-4e69-8590-66aedae4c47f.txt

Snippet of error:

```
T+6.333s [133/2626] Performing download step (download, verify and extract) for 'googleapis_download'
FAILED: external/googleapis/src/googleapis_download-stamp/googleapis_download-download 
cd /workspace/cmake-out/external/googleapis/src && /usr/bin/cmake -P /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/download-googleapis_download.cmake && /usr/bin/cmake -P /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/verify-googleapis_download.cmake && /usr/bin/cmake -P /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/extract-googleapis_download.cmake && /usr/bin/cmake -E touch /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/googleapis_download-download
-- Downloading...
   dst='/workspace/cmake-out/external/googleapis/src/16b43024639e5bcbb0f0367230db654f02cb8499.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/googleapis/googleapis/archive/16b43024639e5bcbb0f0367230db654f02cb8499.tar.gz'
-- [download 100% complete]
-- [download 0% complete]
CMake Error at googleapis_download-stamp/download-googleapis_download.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/googleapis/googleapis/archive/16b43024639e5bcbb0f0367230db654f02cb8499.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
            Trying 140.82.112.4:443...

  Connected to github.com (140.82.112.4) port 443 (#0)
...
```

It looks to me like a transient error w/ github servers.

### PR DESCRIPTION
**Pull request by coryan**
Use GCS as a backup source for the tarball. I changed the script that updates the googleapis SHA to populate this backup at the same time.

Fixes #8102

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9819)

### CODE REVIEW

File: external/googleapis/renovate.sh [hunk 1]
```diff
@@ -20,13 +20,16 @@ REPO="googleapis/googleapis"
 BRANCH="master"
 COMMIT=$(curl -sSL -H "Accept: application/vnd.github.VERSION.sha" \
   "https://api.github.com/repos/${REPO}/commits/${BRANCH}")
-SHA256=$(curl -sSL "https://github.com/${REPO}/archive/${COMMIT}.tar.gz" |
-  sha256sum | sed "s/ .*//")
+DOWNLOAD="$(mktemp)"
+curl -sSL "https://github.com/${REPO}/archive/${COMMIT}.tar.gz" -o "${DOWNLOAD}"
+gsutil -q cp "${DOWNLOAD}" "gs://cloud-cpp-community-archive/com_google_googleapis/${COMMIT}.tar.gz"
+SHA256=$(sha256sum "${DOWNLOAD}" | sed "s/ .*//")
```
Comment (devbww) [inline external/googleapis/renovate.sh:26]: Add `rm -f "${DOWNLOAD}"`?

**Review by devbww — APPROVED** [review]
