### PR TITLE
fix(common): pagination must support empty pages

### LINKED ISSUE #11936: Pagination APIs can stop too early
The wrappers that convert pagination APIs into ranges (and iterators) may stop too early if the service returns a page with no empty and a non-empty pagination token.

Normally I do not create bugs for things fixed with a simple PR.  In this case I think it would be useful to have something to link to.

### PR DESCRIPTION
**Pull request by coryan**
Some services return empty pages with a non-empty pagination token. Our code would stop such iterations immediately. The correct behavior is to retrieve the next page until some non-empty range is returned.

Fixes #11936

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11937)

### CODE REVIEW

**Review by devbww — APPROVED** [review]

File: google/cloud/internal/pagination_range.h [hunk 1]
```diff
@@ -93,18 +93,17 @@ class PagedStreamReader {
...
       if (!response.ok()) return std::move(response).status();
       token_ = ExtractPageToken(*response);
       if (token_.empty()) last_page_ = true;
       page_ = extractor_(*std::move(response));
       current_ = page_.begin();
-      if (current_ == page_.end()) return Status{};
     }
-    return std::move(*current_++);
+    if (current_ != page_.end()) return std::move(*current_++);
+    return Status{};
```
Comment (devbww) [inline google/cloud/internal/pagination_range.h:106]: [Oops ... a comment seems to have been lost ... undoubtedly my mistake.]

Opt nit:  I would reverse the logic here.
```
    if (current_ == page_.end()) return Status{};
    return std::move(*current_++);
```

**Review by devbww — APPROVED** [review]

File: google/cloud/internal/pagination_range.h (hunk 1 above)
Comment (coryan) [reply google/cloud/internal/pagination_range.h]: Done.
