### PR TITLE
test: deflake CompletionQueue test

### LINKED ISSUE #5440: [Flake] CompletionQueueTest failure
I think this test fails under load, in a good way, the CompletionQueue is more efficient than the test expects it to be.

https://source.cloud.google.com/results/invocations/925a10b4-8427-4fa8-b40d-f738ef556b0c

```
258/313 Test  #30: common_grpc_utils_completion_queue_test ............................***Failed   10.41 sec
Running main() from gmock_main.cc
[==========] Running 31 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 25 tests from CompletionQueueTest
[ RUN      ] CompletionQueueTest.TimerCancel
[       OK ] CompletionQueueTest.TimerCancel (440 ms)
[ RUN      ] CompletionQueueTest.TimerSmokeTest
[       OK ] CompletionQueueTest.TimerSmokeTest (2 ms)
[ RUN      ] CompletionQueueTest.MockSmokeTest
[       OK ] CompletionQueueTest.MockSmokeTest (1 ms)
[ RUN      ] CompletionQueueTest.ShutdownWithPending
[       OK ] CompletionQueueTest.ShutdownWithPending (501 ms)
[ RUN      ] CompletionQueueTest.ShutdownWithPendingFake
[       OK ] CompletionQueueTest.ShutdownWithPendingFake (0 ms)
[ RUN      ] CompletionQueueTest.CanCancelAllEvents
[       OK ] CompletionQueueTest.CanCancelAllEvents (2 ms)
[ RUN      ] CompletionQueueTest.MakeUnaryRpc
[       OK ] CompletionQueueTest.MakeUnaryRpc (1 ms)
[ RUN      ] CompletionQueueTest.MakeStreamingReadRpc
[       OK ] CompletionQueueTest.MakeStreamingReadRpc (0 ms)
[ RUN      ] CompletionQueueTest.MakeRpcsAfterShutdown
[       OK ] CompletionQueueTest.MakeRpcsAfterShutdown (0 ms)
[ RUN      ] CompletionQueueTest.RunAsync
[       OK ] CompletionQueueTest.RunAsync (1 ms)
[ RUN      ] CompletionQueueTest.RunAsyncVoid
[       OK ] CompletionQueueTest.RunAsyncVoid (1 ms)
[ RUN      ] CompletionQueueTest.RunAsyncCompletionQueueDestroyed
[       OK ] CompletionQueueTest.RunAsyncCompletionQueueDestroyed (0 ms)
[ RUN      ] CompletionQueueTest.RunAsyncMoveOnly
[       OK ] CompletionQueueTest.RunAsyncMoveOnly (5 ms)
[ RUN      ] CompletionQueueTest.RunAsyncMoveOnlyVoid
[       OK ] CompletionQueueTest.RunAsyncMoveOnlyVoid (0 ms)
[ RUN      ] CompletionQueueTest.RunAsyncThread
[       OK ] CompletionQueueTest.RunAsyncThread (68 ms)
[ RUN      ] CompletionQueueTest.RunAsyncParallel
[       OK ] CompletionQueueTest.RunAsyncParallel (125 ms)
[ RUN      ] CompletionQueueTest.RunAsyncSingleThreaded
[       OK ] CompletionQueueTest.RunAsyncSingleThreaded (101 ms)
[ RUN      ] CompletionQueueTest.RunAsyncSingleThread
[       OK ] CompletionQueueTest.RunAsyncSingleThread (33 ms)
[ RUN      ] CompletionQueueTest.NoRunAsyncAfterShutdown
[       OK ] CompletionQueueTest.NoRunAsyncAfterShutdown (2 ms)
[ RUN      ] CompletionQueueTest.ShutdownWithReschedulingTimer
[       OK ] CompletionQueueTest.ShutdownWithReschedulingTimer (1002 ms)
[ RUN      ] CompletionQueueTest.ShutdownWithFastReschedulingTimer
[       OK ] CompletionQueueTest.ShutdownWithFastReschedulingTimer (9 ms)
[ RUN      ] CompletionQueueTest.CancelAndShutdownWithReschedulingTimer
[       OK ] CompletionQueueTest.CancelAndShutdownWithReschedulingTimer (4 ms)
[ RUN      ] CompletionQueueTest.CancelTimerSimple
[       OK ] CompletionQueueTest.CancelTimerSimple (0 ms)
[ RUN      ] CompletionQueueTest.CancelTimerContinuation
[       OK ] CompletionQueueTest.CancelTimerContinuation (12 ms)
[ RUN      ] CompletionQueueTest.ImplStartOperationDuplicate

[WARNING] /var/tmp/build/googletest/src/gtest-death-test.cc:1122:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 4 threads. See https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#death-tests-and-threads for more explanation and suggested solutions, especially if this is the last message you see before your test times out.
[       OK ] CompletionQueueTest.ImplStartOperationDuplicate (136 ms)
[----------] 25 tests from CompletionQueueTest (2446 ms total)

[----------] 6 tests from RunAsyncTest/RunAsyncTest
[ RUN      ] RunAsyncTest/RunAsyncTest.Torture/0
[       OK ] RunAsyncTest/RunAsyncTest.Torture/0 (812 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.Torture/1
../../google/cloud/completion_queue_test.cc:668: Failure
Expected: (impl->run_async_pool_hwm()) >= (GetParam() / 2), actual: 1 vs 2
[  FAILED  ] RunAsyncTest/RunAsyncTest.Torture/1, where GetParam() = 4 (6825 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.Torture/2
[       OK ] RunAsyncTest/RunAsyncTest.Torture/2 (136 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.TortureBursts/0
[       OK ] RunAsyncTest/RunAsyncTest.TortureBursts/0 (25 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.TortureBursts/1
[       OK ] RunAsyncTest/RunAsyncTest.TortureBursts/1 (55 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.TortureBursts/2
[       OK ] RunAsyncTest/RunAsyncTest.TortureBursts/2 (91 ms)
[----------] 6 tests from RunAsyncTest/RunAsyncTest (7945 ms total)

[----------] Global test environment tear-down
[==========] 31 tests from 2 test suites ran. (10392 ms total)
[  PASSED  ] 30 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RunAsyncTest/RunAsyncTest.Torture/1, where GetParam() = 4

 1 FAILED TEST
```

### PR DESCRIPTION
**Pull request by coryan**
Fixes #5440

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5442)

### CODE REVIEW

File: google/cloud/completion_queue_test.cc [hunk 1]
```diff
@@ -706,7 +706,15 @@ TEST_P(RunAsyncTest, TortureBursts) {
 
   auto constexpr kBurstCount = 100;
   auto const burst_size = GetParam() * kThreads * 8;
-  for (int i = 0; i != kBurstCount; ++i) burst(burst_size);
+  for (int i = 0; i != kBurstCount; ++i) {
+    // On the single-threaded case, the CQ may have DrainAsyncOnIdle() calls
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:710]: s/On/In/?

**Review by devbww — APPROVED** [review]
