### PR TITLE
fix(storage): only backoff before resume attempts

### LINKED ISSUE #14424: Client library sleeps after successfully resuming a download
**Does this issue affect the google-cloud-cpp project?** 

Yes.

**What component of `google-cloud-cpp` is this related to?**

Storage.

**Describe the bug**

When resuming an interrupted download the client library sleeps before each attempt to resume. That is normal, and expected. But it also sleeps **after** the connection is successfully resumed:

https://github.com/googleapis/google-cloud-cpp/blob/f58befb17b9e15c0e4917ae93713065672ddaca7/google/cloud/storage/internal/retry_object_read_source.cc#L77

https://github.com/googleapis/google-cloud-cpp/blob/f58befb17b9e15c0e4917ae93713065672ddaca7/google/cloud/storage/internal/retry_object_read_source.cc#L151

**To Reproduce** Steps to reproduce the behavior:

Very hard to repro in practice. I am filing this

**Expected behavior** A clear and concise description of what you expected to
happen.

No extra sleeps after a successfully resumed connection.

**Operating system:** If you are using a Linux distribution please include the
name and version of the distribution too.

All.

**What compiler and version are you using?** Please include the output of
`g++ -v` or `clang++ -v` or the equivalent command-line flag.

All.

**What version of `google-cloud-cpp` are you using?** Please include the output
from `git rev-parse HEAD` if you are compiling from source, or the version
number from the applicable `google/cloud/*/version.h` file.

Anything that includes https://github.com/googleapis/google-cloud-cpp/commit/8bef9bbf4193bc63d8595e1cd064ebccb961e093, that is, all releases after v1.41.0

**Additional context** Add any other context about the problem here.

I will send a PR shortly, but I want a documented bug in case anybody runs into this problem.

### PR DESCRIPTION
**Pull request by coryan**
`storage::Client::ReadObject()` resumes a download that gets
interrupted (controlled by policy). Before making a resume attempt, the
library backsoff in case the problem is load related. The library was
*also* backing off before issuing the first `Read()` on the newly
created source of data. That effectively doubles the backoff time.

Fixes #14424

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/14427)

### CODE REVIEW

File: google/cloud/storage/internal/retry_object_read_source_test.cc [hunk 1]
```diff
@@ -269,6 +272,50 @@ TEST(RetryObjectReadSourceTest, RetryPolicyExhaustedOnResetSession) {
...
+
+  auto source = std::make_unique<MockObjectReadSource>();
+  {
+    ::testing::InSequence sequence;
+    EXPECT_CALL(*source, Read)
+        .WillOnce(Return(ReadSourceResult{static_cast<std::size_t>(512 * 1024),
+                                          HttpResponse{100, "", {}}}));
+    EXPECT_CALL(*source, Read).WillOnce(Return(TransientError()));
+    // No backoffs to resume after a (partially) successful request:
+    //    EXPECT_CALL(backoff, Call).Times(1);
```
Comment (dbolduc) [inline google/cloud/storage/internal/retry_object_read_source_test.cc:296]: remove?

File: google/cloud/storage/internal/retry_object_read_source_test.cc [hunk 2]
```diff
@@ -222,21 +224,22 @@ TEST(RetryObjectReadSourceTest, BackoffPolicyResetOnSuccess) {
```
Comment (dbolduc) [inline google/cloud/storage/internal/retry_object_read_source_test.cc:224]: s/closed/cloned/ on L217

**Review by dbolduc — APPROVED** [review]

File: google/cloud/storage/internal/retry_object_read_source_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_object_read_source_test.cc]: Done.

File: google/cloud/storage/internal/retry_object_read_source_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_object_read_source_test.cc:224]: Done.
