### PR TITLE
fix(pubsub): dont move PublisherOptions that we are still using

### LINKED ISSUE #7006: [Flake] Pubsub Flow Control times out
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/70f92a9acc238daa2fc13ddf8dbb37156be8c0ce/fedora-34-libcxx/log-0660cabf-78f0-424d-bcbf-69b96658c8e0.txt
```
Step #3: TIMEOUT: //google/cloud/pubsub:publisher_connection_test (Summary)
Step #3:       /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/pubsub/publisher_connection_test/test.log
Step #3: INFO: From Testing //google/cloud/pubsub:publisher_connection_test:
Step #3: ==================== Test output for //google/cloud/pubsub:publisher_connection_test:
Step #3: Running main() from gmock_main.cc
Step #3: [==========] Running 11 tests from 1 test suite.
Step #3: [----------] Global test environment set-up.
Step #3: [----------] 11 tests from PublisherConnectionTest
Step #3: [ RUN      ] PublisherConnectionTest.Basic
Step #3: E0716 14:56:45.948159349      12 credentials_generic.cc:35]  Could not get HOME environment variable.
Step #3: [       OK ] PublisherConnectionTest.Basic (19 ms)
Step #3: [ RUN      ] PublisherConnectionTest.Metadata
Step #3: E0716 14:56:45.967836880      12 credentials_generic.cc:35]  Could not get HOME environment variable.
Step #3: [       OK ] PublisherConnectionTest.Metadata (26 ms)
Step #3: [ RUN      ] PublisherConnectionTest.Logging
Step #3: E0716 14:56:45.994248927      12 credentials_generic.cc:35]  Could not get HOME environment variable.
Step #3: [       OK ] PublisherConnectionTest.Logging (18 ms)
Step #3: [ RUN      ] PublisherConnectionTest.FlowControl
Step #3: E0716 14:56:46.012879941      12 credentials_generic.cc:35]  Could not get HOME environment variable.
Step #3: -- Test timed out at 2021-07-16 15:01:45 UTC --
```

I was able to reproduce once locally with: 
```
bazel test --nocache_test_results --runs_per_test=100 //google/cloud/pubsub:publisher_connection_test
```
But even that will only fail every couple of runs.

### PR DESCRIPTION
**Pull request by dbolduc**
we `std::move(options)` in the `make_connection` lambda which captures by reference. Then we keep using `options`... 

I am not sure how to test for this change.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7270)

### CODE REVIEW

**Review by coryan — DISMISSED** [review]

File: google/cloud/pubsub/publisher_connection.cc [hunk 1]
```diff
@@ -138,13 +138,13 @@ std::shared_ptr<pubsub::PublisherConnection> MakePublisherConnection(
     if (options.message_ordering()) {
       auto factory = [topic, options, sink, cq](std::string const& key) {
         return BatchingPublisherConnection::Create(
-            topic, options, key, SequentialBatchSink::Create(std::move(sink)),
-            cq);
+            std::move(topic), std::move(options), key,
```
Comment (coryan) [inline google/cloud/pubsub/publisher_connection.cc:141]: I do not think you want to `std::move` here. `factory` may be called multiple times, once for each ordering key that is discovered (dynamically).  You want a copy, and note that they are captured by copy too.

File: google/cloud/pubsub/publisher_connection.cc [hunk 2]
```diff
@@ -138,13 +138,13 @@ std::shared_ptr<pubsub::PublisherConnection> MakePublisherConnection(
...
+            SequentialBatchSink::Create(std::move(sink)), std::move(cq));
       };
       return OrderingKeyPublisherConnection::Create(std::move(factory));
     }
     return RejectsWithOrderingKey::Create(BatchingPublisherConnection::Create(
-        std::move(topic), std::move(options), {}, sink, std::move(cq)));
+        topic, options, {}, std::move(sink), std::move(cq)));
```
Comment (coryan) [inline google/cloud/pubsub/publisher_connection.cc:147]: This is called at most once, and therefore a `std::move(topic)` was appropriate.

File: google/cloud/pubsub/publisher_connection.cc [hunk 3]
```diff
@@ -138,13 +138,13 @@ std::shared_ptr<pubsub::PublisherConnection> MakePublisherConnection(
...
   };
   auto connection = make_connection();
```
Comment (coryan) [inline google/cloud/pubsub/publisher_connection.cc:149]: I am beginning to think this is too clever for its own good.

Maybe we should do this (starting around line 133):


```cc
auto cp = background->cq();
auto sink = DefaultBatchSink::Create(stub, cq, std::move(retry_policy), std::move(backoff_policy));
auto connection = RejectsWithOrderingKey::Create(BatchingPublisherConnection::Create(topic, options, {}, sink, cq);
if (options.message_ordering()) {
  auto factory = [topic, options, sink, cq](std::string const& key) {
    return BatchingPublisherConnection::Create(topic, options, key, SequentialBatchSink(std::move(sink), std::move(cq)));
  };
  connection = OrderKeyPublisherConnection(std::move(factory));
}
```

It makes a few more copies than it should, but it is probably more readable.  Alternatively, moving the lambda to a function may make it more obvious.  Your call.

**Review by coryan — CHANGES_REQUESTED** [review]

File: google/cloud/pubsub/publisher_connection.cc (hunk 3 above)
Comment (dbolduc) [reply google/cloud/pubsub/publisher_connection.cc:148]: I think the code is fine. I like that `BatchingPublisherConnection::Create()` is only called once

File: google/cloud/pubsub/publisher_connection.cc (hunk 2 above)
Comment (dbolduc) [reply google/cloud/pubsub/publisher_connection.cc]: whoops

File: google/cloud/pubsub/publisher_connection.cc (hunk 1 above)
Comment (dbolduc) [reply google/cloud/pubsub/publisher_connection.cc]: Fixed.

**Review by coryan — APPROVED** [review]
