### PR TITLE
Change bigtable::FailedMutation to work with google::cloud::Status

### LINKED ISSUE #2003: Change Table::BulkApply to work with StatusOr.
When there are failed mutations, `google::cloud::bigtable::Table::BulkApply` raises an exception with the failed mutations. We should change this function to not require exceptions.

I am not certain of the right solution, so I will propose some ideas below.

### PR DESCRIPTION
**Pull request by rsimion**
Part of the work for #2003.  Prepares `FailedMutation` to work with `google::cloud::Status`. We want to return a consistent `Status` type.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2108)

### CODE REVIEW

**Comment by rsimion** [comment]
@coryan 
FailedMutation only, for now

File: google/cloud/bigtable/mutations.h [hunk 1]
```diff
@@ -319,6 +324,7 @@ class FailedMutation {
   /// @name accessors
   SingleRowMutation const& mutation() const { return mutation_; }
   grpc::Status const& status() const { return status_; }
+  google::cloud::Status const& gcstatus() const { return gcstatus_; }
```
Comment (coryan) [inline google/cloud/bigtable/mutations.h]: I think I was not specific enough.  I think this should be:

```C++
  google::cloud::Status const& status() const { return status_; }
  // no gcstatus() function
```

And we should change all the code to deal with that new API (yup, it would be a big change).

Comment (rsimion) [reply google/cloud/bigtable/mutations.h]: So in FailedMutation class, remove the ```grpc::Status status_``` variable, its accessor and the constructor that takes in a ```google::rpc::Status``` and converts it into a  ```grpc::Status status_``` and the static function that does that
and  have only  a ```google::cloud::Status status_``` , its accessor and the constructor that takes in a   ```google::cloud::Status status_```, correct?

Comment (coryan) [reply google/cloud/bigtable/mutations.h]: Correct.

**Comment by rsimion** [comment]
@coryan

How about this? 
```
class FailedMutation {
 public: 

  FailedMutation(SingleRowMutation mut, google::cloud::Status status, int index)
      : mutation_(std::move(mut)), status_(status), original_index_(index) {}

  FailedMutation(SingleRowMutation mut, google::rpc::Status status, int index)
      : mutation_(std::move(mut)),       
        status_(ToGCStatus(status)),
        original_index_(index) {}
        
  FailedMutation(FailedMutation&&) = default;
  FailedMutation& operator=(FailedMutation&&) = default;
  FailedMutation(FailedMutation const&) = default;
  FailedMutation& operator=(FailedMutation const&) = default;

  //@{
  /// @name accessors
  SingleRowMutation const& mutation() const { return mutation_; }
  //grpc::Status const& status() const { return status_; }
  google::cloud::Status const& status() const { return status_; }
  int original_index() const { return original_index_; }
  //@}

  friend class BulkMutation;

 private:
  static grpc::Status ToGrpcStatus(google::rpc::Status const& status);
  static google::cloud::Status ToGCStatus(google::rpc::Status const& status);

 private:
  SingleRowMutation mutation_;  
  google::cloud::Status status_;
  int original_index_;
};
```
with

```
google::cloud::Status FailedMutation::ToGCStatus(google::rpc::Status const& rpc_status) {
	grpc::Status grpc_status = FailedMutation::ToGrpcStatus(rpc_status);
	return  bigtable::internal::MakeStatusFromRpcError(grpc_status); 	
}
```

If I have only one constructor  that takes in a ```google::cloud::Status``` then a lot of files 
 will be affected 
 
 /bigtable
 mutation_batcher.cc, mutations.h, mutations.cc mutations_test.cc, table.cc 
 /bigtabl/internal
 async_bulk_apply,bulk_mutator.cc,bulk_mutator.h,table_async_bulk_apply_test.cc,table.cc,table.h
 table_test.cc  
  
 If we start with those 2 constructors it is easier to change the status first and make a smooth transition. 
 I still have to modify some files but only what relates to the new status type.

**Comment by coryan** [comment]
That sounds reasonable.  Starting with two constructors and then we can remove the extra one in a future PR.

**Comment by rsimion** [comment]
@coryan 
I have commented out and not removed yet the lines that are currently in the master branch for easy comparison.
I will remove them after you agree with my changes. Then I will push the changes for BulkApply.

**Comment by rsimion** [comment]
Table::AsyncBulkApply I will change it later, I cannot yet return resultfm, the compiler expects a ```future<void>```.

First I want to commit all the changes for BulkApply after you agree with all the changes for FailedMutation.
