### PR TITLE
fix(storage): avoid crashes when parsing `ErrorInfo`

### LINKED ISSUE #8965: google storage client json throw exception when http request fails
**What component of `google-cloud-cpp` is this related to?**
GCS

**Describe the bug**
When http response fails, it would rely on json library to get detailed error message.
Code here: https://github.com/googleapis/google-cloud-cpp/blob/643fa047a549422ebaa40f9173ab0c2c8372aede/google/cloud/storage/internal/http_response.cc#L172

Sample http response-1:
```
{\"error\":\"invalid_grant\",\"error_description\":\"Invalid grant: account not found\"}
```
Exception stacktrace:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.306] cannot use value() with string
```
Using some logging, the exception happens: https://github.com/googleapis/google-cloud-cpp/blob/643fa047a549422ebaa40f9173ab0c2c8372aede/google/cloud/storage/internal/http_response.cc#L189

Sample http response-2:
```
Service Unavailable
```
Exception stacktrace:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.306] cannot use value() with string
```
With some logging the error happens:
https://github.com/googleapis/google-cloud-cpp/blob/643fa047a549422ebaa40f9173ab0c2c8372aede/google/cloud/storage/internal/http_response.cc#L175

**Expected behavior**
No exception would be thrown.

**Operating system:**
ubuntu 20

**What compiler and version are you using?**
clang v13.0.0

**What version of `google-cloud-cpp` are you using?**
v1.38.0

**Additional information**
I tried to reproduce locally with the above error response, but cannot repro it.
I want you to give me some intuitions.

### PR DESCRIPTION
**Pull request by coryan**
Maybe unsurprisingly, the error payloads are less structured that we
expected. This PR performs additional validation to avoid crashes while
trying to parse these payloads as a `ErrorInfo`.  If we could reliably
use exceptions I would just parse the code and handle any exception in
a single line of code, alas, we cannot.

Fixes #8965

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8968)

### CODE REVIEW

File: google/cloud/storage/internal/http_response.cc [hunk 1]
```diff
@@ -186,11 +194,13 @@ Status AsStatus(HttpResponse const& http_response) {
...
-  auto error = json.value("error", nlohmann::json::object());
-  auto message = error.value("message", http_response.payload);
-  auto details = error.value("details", nlohmann::json::object());
-  auto error_info = MakeErrorInfo(details);
-  return Status(status_code, std::move(message), std::move(error_info));
+  if (!json.contains("error")) return default_error();
+  auto const& e = json["error"];
+  if (!e.is_object()) return default_error();
+  if (!e.contains("message") || !e.contains("details")) return default_error();
+  if (!e["message"].is_string()) return default_error();
```
Comment (dbolduc) [inline google/cloud/storage/internal/http_response.cc:201]: We could return a `Status(code, e.value("message", ""))` if `e.contains("message") && e["message"].is_string() && !e.contains("details")`, but it's also fine to return the whole payload as a message.

**Review by dbolduc — APPROVED** [review]

File: google/cloud/storage/internal/http_response.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/http_response.cc:201]: Ack
