### PR TITLE
test(common): deflake `TimerQueue` test

### LINKED ISSUE #10535: TimerQueueTest.ScheduleEarlierTimerMultipleRunner later.is_ready() expectation failure
```
[ RUN      ] TimerQueueTest.ScheduleEarlierTimerMultipleRunner
/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/google/cloud/internal/timer_queue_test.cc:151: Failure
Value of: later.is_ready()
  Actual: true
Expected: false
[  FAILED  ] TimerQueueTest.ScheduleEarlierTimerMultipleRunner (233 ms)
```
https://source.cloud.google.com/results/invocations/9a62ff95-0da1-45af-bcd3-9fdc80d89b52/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmain%2Fmacos%2Fcmake-vcpkg-presubmit/log

### PR DESCRIPTION
**Pull request by coryan**
Fixes #10535.  Or rather, I think that was fixed by the earlier changes to test for equality in the expiration times, but that made the test kind of trivial.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/10560)

### CODE REVIEW

File: google/cloud/internal/timer_queue_test.cc [hunk 1]
```diff
@@ -76,27 +78,58 @@ TEST(TimerQueueTest, CancelTimers) {
...
+  std::vector<std::chrono::system_clock::time_point> actual;
+  std::vector<future<Status>> timers(expected.size());
+  std::transform(expected.begin(), expected.end(), timers.begin(), [&](auto d) {
+    // As the timers expire we add their time (if successful) to `expirations`,
+    // and return the `Status`.
+    return tq->Schedule(d).then([&, d](auto f) {
+      auto e = f.get();
+      if (!e) return std::move(e).status();
+      std::ostringstream os;
+      os << "mismatched " << d << " != " << *e;
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:111]: Move this into the actual `*e != d` block?

File: google/cloud/internal/timer_queue_test.cc [hunk 2]
```diff
@@ -76,27 +78,58 @@ TEST(TimerQueueTest, CancelTimers) {
...
-                                 .get();
-  auto later_expire_time = later.get();
+
+  // Wait for all the timers to expire.
+  std::vector<Status> status(timers.size());
+  std::transform(timers.begin(), timers.end(), status.begin(),
+                 [](auto& f) { return f.get(); });
+  EXPECT_THAT(status, Each(IsOk()));
+
+  // At this  We expect the expirations to be in order and match the provided
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:127]: s/this  We expect/this point we expect/?

File: google/cloud/internal/timer_queue_test.cc [hunk 3]
```diff
@@ -76,27 +78,58 @@ TEST(TimerQueueTest, CancelTimers) {
...
+  // Create the timer queue, but do not run the servicing thread until the
+  // timers are scheduled. Otherwise "later" timers may be immediately expired
+  // because clocks are hard.
   auto tq = TimerQueue::Create();
+
+  auto const start = std::chrono::system_clock::now();
+  std::vector<std::chrono::system_clock::time_point> expected(delays.size());
+  std::transform(delays.begin(), delays.end(), expected.begin(),
+                 [start](auto d) { return start + d; });
+  // We are going to store the expiration of each timer in this vector, we do
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:99]: s/vector, we/vector. We/

File: google/cloud/internal/timer_queue_test.cc [hunk 4]
```diff
@@ -76,27 +78,58 @@ TEST(TimerQueueTest, CancelTimers) {
...
+  // not need to protect it with a mutex because only one thread operates on
+  // it at a time.
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:101]: Being able to say "only one thread operates on it at a time" implies there is synchronization between the threads, which I agree there is (satisfying the future happens before retrieving its value).  So, I might say something that explains that synchronization: _"Access to `actual` is synchronized between the serving thread and the test thread via ..."_.

File: google/cloud/internal/timer_queue_test.cc [hunk 5]
```diff
@@ -76,27 +78,58 @@ TEST(TimerQueueTest, CancelTimers) {
...
+
+  // Wait for all the timers to expire.
+  std::vector<Status> status(timers.size());
+  std::transform(timers.begin(), timers.end(), status.begin(),
+                 [](auto& f) { return f.get(); });
+  EXPECT_THAT(status, Each(IsOk()));
+
+  // At this  We expect the expirations to be in order and match the provided
+  // times.
+  EXPECT_THAT(expected, WhenSorted(ElementsAreArray(actual)));
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:129]: To make synchronization of `actual` even more obvious (i.e., probably not even requiring a comment), you could move this expectation after the `join()`.

File: google/cloud/internal/timer_queue_test.cc [hunk 6]
```diff
@@ -76,27 +78,58 @@ TEST(TimerQueueTest, CancelTimers) {
...
+  std::vector<future<Status>> timers(expected.size());
+  std::transform(expected.begin(), expected.end(), timers.begin(), [&](auto d) {
+    // As the timers expire we add their time (if successful) to `expirations`,
+    // and return the `Status`.
+    return tq->Schedule(d).then([&, d](auto f) {
+      auto e = f.get();
+      if (!e) return std::move(e).status();
+      std::ostringstream os;
+      os << "mismatched " << d << " != " << *e;
+      if (*e != d) return Status(StatusCode::kUnknown, std::move(os).str());
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:112]: I might choose `kFailedPrecondition` or `kInternal` before `kUnknown`.

File: google/cloud/internal/timer_queue_test.cc [hunk 7]
```diff
@@ -76,27 +79,62 @@ TEST(TimerQueueTest, CancelTimers) {
...
   tq->Shutdown();
   t.join();
 
-  ASSERT_THAT(earlier_expire_time, IsOk());
-  ASSERT_THAT(later_expire_time, IsOk());
-  EXPECT_EQ(*earlier_expire_time, now + duration);
-  EXPECT_EQ(*later_expire_time, now + 2 * duration);
+  EXPECT_THAT(status, Each(IsOk()));
+
+  // At this point we expect the expirations to be in order and match the\
```
Comment (devbww) [inline google/cloud/internal/timer_queue_test.cc:135]: s/\$//

**Review by devbww — APPROVED** [review]

File: google/cloud/internal/timer_queue_test.cc (hunk 7 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Argh, fixed.

File: google/cloud/internal/timer_queue_test.cc (hunk 6 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Done.

File: google/cloud/internal/timer_queue_test.cc (hunk 5 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Done, but I left the comments.

File: google/cloud/internal/timer_queue_test.cc (hunk 4 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Done.

File: google/cloud/internal/timer_queue_test.cc (hunk 3 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Fixed.

File: google/cloud/internal/timer_queue_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Done.

File: google/cloud/internal/timer_queue_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/internal/timer_queue_test.cc]: Done
