### PR TITLE
fix(otel): reconnect async traces (e.g. LROs)

### LINKED ISSUE #13141: Reconnect async traces with backoffs
I introduced a new bug in the implementation of #12880. I thought I was being helpful by having `EndSpan(..., future<T>)` detach the current context. Well, if we don't attach a context for the operation first, we run into problems. This happens in `TracedAsyncBackoff()`.

We currently get broken traces like:
image

We want traces like:
image

Aside: more evidence that we could use something like #13034

### PR DESCRIPTION
**Pull request by dbolduc**
Fixes #13141 

See the linked issue for the problem write up. The changes in this PR generated the seemingly correct, second screenshot.

The ABI update was necessary because we stop defining some templated `future<StatusOr<std::chrono::...>>` type, which triggered a false positive in `check-api`.

Something is buggy with (at least) `opentelemetry-cpp` + `gcc 7.3.1`. So patch the Dockerfile used in that build to work around it.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13147)

### CODE REVIEW

**Comment by dbolduc** [comment]
Ugh, the gcc-7-3 error is out of our control. I need to think about how we can avoid it in our repo.

The following code reproduces the same error. It does not use any `google-cloud-cpp` helpers. Some bug in the compiler causes this basic, `opentelemetry-cpp` test to fail.

```cc
TEST(OpenTelemetry, DarrenOTelOnly) {
  auto span_catcher = InstallSpanCatcher();

  auto provider = opentelemetry::trace::Provider::GetTracerProvider();
  auto tracer = provider->GetTracer("gcc-7-3 test");

  auto parent = tracer->StartSpan("parent");
  opentelemetry::trace::Scope parent_scope(parent);

  auto child = tracer->StartSpan("child");
  child->End();

  parent->End();

  EXPECT_THAT(
      span_catcher->GetSpans(),
      ElementsAre(AllOf(SpanNamed("child"),
                        SpanWithParentSpanId(parent->GetContext().span_id())),
                  SpanNamed("parent")));
}
```

```
[ RUN      ] OpenTelemetry.DarrenOTelOnly
../google/cloud/internal/grpc_opentelemetry_test.cc:279: Failure
Value of: span_catcher->GetSpans()
Expected: has 2 elements where
element #0 (has name: child) and (has parent span id: 5d48e34bfafc4edb),
element #1 has name: parent
  Actual: { (ptr = 0x1f422a0, value = Span {name=child, kind=INTERNAL, instrumentation_scope {gcc-7-3 test, },
			parent_span_id=0000000000000000
			attributes=[],
			events=[],
			links=[]}), (ptr = 0x1f42c20, value = Span {name=parent, kind=INTERNAL, instrumentation_scope {gcc-7-3 test, },
			parent_span_id=0000000000000000
			attributes=[],
			events=[],
			links=[]}) }, whose element #0 doesn't match, has parent span id: 0000000000000000

[  FAILED  ] OpenTelemetry.DarrenOTelOnly (0 ms)
```

File: google/cloud/internal/grpc_opentelemetry_test.cc [hunk 1]
```diff
@@ -208,6 +210,52 @@ TEST(OpenTelemetry, TracedAsyncBackoffDisabled) {
   EXPECT_THAT(spans, IsEmpty());
 }
 
+TEST(OpenTelemetry, TracedAsyncBackoffPreservesContext) {
+  if (CompilerId() == "GNU" && CompilerVersion() == "7.3.1") {
```
Comment (coryan) [inline google/cloud/internal/grpc_opentelemetry_test.cc:214]: Does OTel claim to support GCC 7.x?  Is there a bug in OTel we can reference?  Can we detect this with an OTel version?

Comment (dbolduc) [reply google/cloud/internal/grpc_opentelemetry_test.cc:214]: > Does OTel claim to support GCC 7.x?

My reading is they support compilers that implement the standard correctly.

> Is there a bug in OTel we can reference?

good idea, and yes: https://github.com/open-telemetry/opentelemetry-cpp/issues/1014

Comment (dbolduc) [reply google/cloud/internal/grpc_opentelemetry_test.cc:214]: There is a patch linked in the issue. I will try to apply it to our `centos-7` dockerfile.

Comment (coryan) [reply google/cloud/internal/grpc_opentelemetry_test.cc:214]: According to some comments on that bug, GCC 8.x also trouble. You may need to apply that patch to several other builds.

Comment (coryan) [reply google/cloud/internal/grpc_opentelemetry_test.cc:214]: > My reading is they support compilers that implement the standard correctly.

There are no compilers without defects.  That implies they support no compilers at all.

Comment (dbolduc) [reply google/cloud/internal/grpc_opentelemetry_test.cc]: Patched.

> According to some comments on that bug, GCC 8.x also trouble. You may need to apply that patch to several other builds.

Thanks for pointing that out. I forgot that the `demo-install` builds do not run these unit tests. I assumed they all worked.

Opened #13159 because I am not sure if we should apply the patch by default, or just call out the issue in a comment.

> There are no compilers without defects. That implies they support no compilers at all.

I realize that and my comment was tongue-in-cheek. Here is their actual text: https://github.com/open-telemetry/opentelemetry-cpp/blob/cb603ad97f33e52340e627e1cb43ba73bb1d7ef0/README.md?plain=1#L48-L49

File: google/cloud/internal/grpc_opentelemetry.h [hunk 2]
```diff
@@ -108,14 +108,16 @@ template <typename Rep, typename Period>
...
     CompletionQueue& cq, Options const& options,
     std::chrono::duration<Rep, Period> duration) {
-  auto timer = cq.MakeRelativeTimer(duration);
 #ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
   if (TracingEnabled(options)) {
-    timer = EndSpan(MakeSpan("Async Backoff"), std::move(timer));
+    auto span = MakeSpan("Async Backoff");
+    OTelScope scope(span);
+    auto timer = cq.MakeRelativeTimer(duration);
+    return EndSpan(span, std::move(timer));
```
Comment (devbww) [inline google/cloud/internal/grpc_opentelemetry.h:116]: `std::move(span)`

Comment (dbolduc) [reply google/cloud/internal/grpc_opentelemetry.h]: Done

**Comment by dbolduc** [comment]
Ping.

(I am not blocked on this PR. It would just be nice to have the fix in.)

**Review by devbww — APPROVED** [review]
