### PR TITLE
test: deflake completion queue test

### LINKED ISSUE #5497: [Flake] CompletionQueue unit test error
I have noticed this in some PRs:

```
[----------] 6 tests from RunAsyncTest/RunAsyncTest
[ RUN      ] RunAsyncTest/RunAsyncTest.Torture/0
[       OK ] RunAsyncTest/RunAsyncTest.Torture/0 (869 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.Torture/1
../../google/cloud/completion_queue_test.cc:640: Failure
Expected: (impl->run_async_pool_hwm()) >= (GetParam() / 2), actual: 1 vs 2
[  FAILED  ] RunAsyncTest/RunAsyncTest.Torture/1, where GetParam() = 4 (6780 ms)
[ RUN      ] RunAsyncTest/RunAsyncTest.Torture/2
[       OK ] RunAsyncTest/RunAsyncTest.Torture/2 (134 ms)
```

https://source.cloud.google.com/results/invocations/75ccbe0e-b506-4705-8acc-d3aaf3497558

I think the test is just too optimistic about how fast threads can start.

### PR DESCRIPTION
**Pull request by coryan**
Fixes #5497

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/5504)

### CODE REVIEW

File: google/cloud/completion_queue_test.cc [hunk 1]
```diff
@@ -637,7 +637,14 @@ TEST_P(RunAsyncTest, Torture) {
   // and/or deadlocks under load. Just getting here is enough to declare
   // success, but we should verify that at least some interesting stuff happened
   EXPECT_GE(impl->thread_pool_hwm(), GetParam() / 2);
-  EXPECT_GE(impl->run_async_pool_hwm(), GetParam() / 2);
+  // We would like to assert "a good portion of the available threads was used
+  // AsyncRun() queue". That is flaky when the "available" threads is small.
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:641]: s/AsyncRun/RunAsync/?

File: google/cloud/completion_queue_test.cc [hunk 2]
```diff
@@ -637,7 +637,14 @@ TEST_P(RunAsyncTest, Torture) {
   // and/or deadlocks under load. Just getting here is enough to declare
   // success, but we should verify that at least some interesting stuff happened
   EXPECT_GE(impl->thread_pool_hwm(), GetParam() / 2);
-  EXPECT_GE(impl->run_async_pool_hwm(), GetParam() / 2);
+  // We would like to assert "a good portion of the available threads was used
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:640]: Maybe "RunAsync() used a good portion of the available threads".

File: google/cloud/completion_queue_test.cc [hunk 3]
```diff
@@ -637,7 +637,14 @@ TEST_P(RunAsyncTest, Torture) {
   // and/or deadlocks under load. Just getting here is enough to declare
   // success, but we should verify that at least some interesting stuff happened
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:638]: Maybe s/$/./ while you're here?

File: google/cloud/completion_queue_test.cc [hunk 4]
```diff
@@ -637,7 +637,14 @@ TEST_P(RunAsyncTest, Torture) {
...
   EXPECT_GE(impl->thread_pool_hwm(), GetParam() / 2);
-  EXPECT_GE(impl->run_async_pool_hwm(), GetParam() / 2);
+  // We would like to assert "a good portion of the available threads was used
+  // AsyncRun() queue". That is flaky when the "available" threads is small.
+  // With one thread obviously just 1 gets used. Even with 4 threads, by design
+  // it will be at most 3, and at least 1, but it does not always hit 2.
+  // It seems all we can do reliably is test for the expected range.
```
Comment (devbww) [inline google/cloud/completion_queue_test.cc:644]: s/expected/entire/ perhaps?

**Review by devbww — APPROVED** [review]
