### PR TITLE
fix: cleanup KOKORO_ARTIFACTS_DIR

### LINKED ISSUE #3618: Potential optimization for clang-tidy build
The `clang-tidy` build is not firmly below 20m, which would be ideal before accepting further libraries into `google-cloud-cpp`.  Looking at the logs for one build which took 21m25s I found this:

```
[ID: 2428702] Build finished after 751 secs, exit value: 0


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[18:25:47] Collecting build artifacts from build VM
[18:32:41] Kokoro builder finished
[18:33:02] Running blaze commands.
[18:33:06] Finished running blaze commands.
[18:33:08] /tmp/workspace/workspace/cloud-cpp/github/google-cloud-cpp/master/docker/clang-tidy-presubmit/artifacts/custom_sponge_config.csv does not exist in the workspace, no custom config value to log
[18:33:16] Updating SpongeV2 invocation.
[18:33:21] Updating ResultStore invocation.
```

Note that the build script completes in about 12m31s, but **after** the script finishes there are roughly 7m spent "Collecting build artifacts".  I suspect this is the same problem as the Windows builds, except that not as bad, removing the `${KOKORO_ARTIFACTS_DIR}` might speed up the builds.

### PR DESCRIPTION
**Pull request by devjgm**
Fixes #3618

I suspect this will shave a few minutes off most of our docker builds.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3637)

### CODE REVIEW

File: ci/kokoro/docker/build.sh [hunk 1]
```diff
@@ -561,6 +561,19 @@ fi
 echo "================================================================"
 "${PROJECT_ROOT}/ci/kokoro/docker/dump-reports.sh"
 
+echo "================================================================"
+if [[ "${RUNNING_CI:-}" == "yes" ]] && [[ -n "${KOKORO_ARTIFACTS_DIR:-}" ]]; then
+  # Our CI system (kokoro) syncs the data in this directory to somewhere after
+  # the build completes. Removing the cmake-out/ dir shaves minutes off this
+  # process. This is safe as long as we don't wish to save any build artifacts.
+  echo "${COLOR_YELLOW}$(date -u): cleaning up artifacts.${COLOR_RESET}"
+  find "${KOKORO_ARTIFACTS_DIR}" -name cmake-out -type d -print0 \
```
Comment (devbww) [inline ci/kokoro/docker/build.sh:570]: You probably want some form of `-depth` or `-prune` here.
