### PR TITLE
fix(storage): improve JSON validation

### LINKED ISSUE #8027: [Flake] error in JSON library in storage signed_url_integration_test.cc
I ran `asan-pr` locally, and ran into the following flake in this test: https://github.com/googleapis/google-cloud-cpp/blob/9c793dae470fd82a9ea86572fb0c8ab4a12ea736/google/cloud/storage/tests/signed_url_integration_test.cc#L132

```
[ RUN      ] SignedUrlIntegrationTest.CreateV4SignedUrlGet
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.306] cannot use value() with string
```

The error message reminds me of this PR: #7702

### PR DESCRIPTION
**Pull request by coryan**
Prefer using `!is_object()` over `is_discarded()` to detect parsing
errors. In many cases this change made no difference (e.g. where there
was an implicit check via `.count()`). In a few places the new tests
triggered latent bugs. One of these bugs was real, but it is hard to say
which one.

Fixes #8027

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/8033)

### CODE REVIEW

File: google/cloud/storage/oauth2/google_credentials_test.cc [hunk 1]
```diff
@@ -445,17 +445,23 @@ TEST_F(GoogleCredentialsTest, LoadUnknownTypeCredentials) {
...
-
-  auto creds = GoogleDefaultCredentials();
-  EXPECT_THAT(creds, StatusIs(StatusCode::kInvalidArgument,
-                              HasSubstr("credentials file " + filename)));
+  char const* const test_cases[] = {
+      R"""( not-a-json-object-string )""",
+      R"js("valid-json-but-not-an-object")js",
+  };
+  for (auto const* contents : test_cases) {
+    SCOPED_TRACE("Testing with: " + std::string{contents});
```
Comment (dbolduc) [inline google/cloud/storage/oauth2/google_credentials_test.cc:453]: TIL: `SCOPED_TRACE()`

**Review by dbolduc — APPROVED** [review]
Thanks for going through and fixing these.
