### PR TITLE
fix(docfx): skip nested namespaces in children list

### LINKED ISSUE #11452: Nested namespaces are listed but there is no title.
image

### PR DESCRIPTION
**Pull request by coryan**
Listing the nested namespaces as children is (arguably) technically correct, but it does not render right, and does not aid in navigation.

Fixes #11452

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/11483)

### CODE REVIEW

**Review by dbolduc — APPROVED** [review]

File: docfx/doxygen2references.cc [hunk 1]
```diff
@@ -48,10 +48,8 @@ std::list<Reference> ExtractReferences(YamlContext const& ctx,
   if (!IncludeInPublicDocuments(ctx.config, node)) return {};
 
   auto const name = std::string_view{node.name()};
-  if (name == "innernamespace") {
-    auto const uid = std::string{node.attribute("refid").as_string()};
-    return {Reference(uid, node.child_value())};
-  }
+  // Skip <innernamespace> elements. They are listed in ToC (the left-side
+  // navigation).
```
Comment (dbolduc) [inline docfx/doxygen2references.cc:52]: Consider adding the following to be explicit
```cc
if (name == "innernamespace") return {};
```

Comment (dbolduc) [reply docfx/doxygen2references.cc:52]: Well, you know better than I whether we should `RecurseReferences` for this case or not.

Comment (coryan) [reply docfx/doxygen2references.cc:52]: Done.
