### PR TITLE
fix(GCS+gRPC): resumable uploads can resume

### LINKED ISSUE #6875: Support resumable uploads with GCS+gRPC
Resumable uploads are not working for GCS+gRPC, I need to troubleshoot and fix any issues, potentially opening bugs with the GCS team.  Several tests are disabled, but for unrelated reasons (e.g. #5460 which has a bad title).  Also these are relevant:

b/172859307
b/147673593
b/146890058

### PR DESCRIPTION
**Pull request by coryan**
To make resumable uploads resumable we need to close the stream after
each chunk, and the byte accounting needed some fixing. I was able to
simplify some of the code after these changes.

In the process I discovered and fixed a bug in the emulator: it did not
handle partial uploads correctly.

The "last committed byte" accounting could use a cleanup, but that is
a matter for a future PR (see #6880).

Fixes #6875.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6881)

### CODE REVIEW

File: google/cloud/storage/tests/auto_finalize_integration_test.cc [hunk 1]
```diff
@@ -90,7 +90,6 @@ TEST_F(AutoFinalizeIntegrationTest, ExplicitlyEnabled) {
 
 TEST_F(AutoFinalizeIntegrationTest, Disabled) {
   // TODO(#6875) - enable this test once GCS+gRPC supports resuming uploads.
-  if (UsingGrpc()) GTEST_SKIP();
```
Comment (devbww) [inline google/cloud/storage/tests/auto_finalize_integration_test.cc:93]: So, remove the TODO too?

**Review by devbww — APPROVED** [review]

File: google/cloud/storage/tests/auto_finalize_integration_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/tests/auto_finalize_integration_test.cc:93]: Done.
