### PR TITLE
Change TableAdmin API to use StatusOr<>.

### LINKED ISSUE #1943: Return StatusOr from bigtable::TableAdmin::GetTable
The signature should look like the following and not throw exceptions.

```c++
StatusOr<::google::bigtable::admin::v2::Table> GetTable(
      std::string const& table_id,
      ::google::bigtable::admin::v2::Table::View view =
          ::google::bigtable::admin::v2::Table::SCHEMA_VIEW);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

### LINKED ISSUE #1944: Return Status from bigtable::TableAdmin::DeleteTable()
Rather than throwing on error, return `Status` as shown below:

```c++
  Status DeleteTable(std::string const& table_id);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example

### LINKED ISSUE #1945: Return Statusor from bigtable::TableAdmin::ModifyColumnFamilies
Rather than throwing on error, return `StatusOr`. The signature should look as follows:

```c++
  StatusOr<::google::bigtable::admin::v2::Table> ModifyColumnFamilies(
      std::string const& table_id,
      std::vector<ColumnFamilyModification> modifications);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

### LINKED ISSUE #1946: Return Status from bigtable::TableAdmin::DropRowsByPrefix
Rather than throwing on error, return `Status`. The signature should look as follows:

```c++
 Status DropRowsByPrefix(std::string const& table_id,
                        std::string row_key_prefix);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 as an example.

### LINKED ISSUE #1947: Return StatusOr from bigtable::TableAdmin::GenerateConsistencyToken
Rather than throwing, return StatusOr. The signature should look as follows:

```c++
  StatusOr<std::string> GenerateConsistencyToken(std::string const& table_id);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 as an examle.

### LINKED ISSUE #1948: Return Status from bigtable::TableAdmin::CheckConsistency
Rather than throwing on error, return `Status`. The signature should look like:

```c++
  Status CheckConsistency(bigtable::TableId const& table_id,
                        bigtable::ConsistencyToken const& consistency_token);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 as an example

NOTE: This function is changing from returning `bool` to returning `Status`. This is slightly different from the other transformations that only change from void -> Status. However, `StatusOr<bool>` is a strange type that's of questionable use. I think a plain Status would be easier to use and have more meaning.

### LINKED ISSUE #1949: Return Status from bigtable::TableAdmin::DropAllRows
Instead of throwing on error, return `Status`. The signature should look as follows:

```c++
  Status DropAllRows(std::string const& table_id);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

### LINKED ISSUE #1950: Return StatusOr from bigtable::TableAdmin::GetSnapshot
Rather than throwing on error, return StatusOr. The signature should look like:

```c++
 StatusOr<google::bigtable::admin::v2::Snapshot> GetSnapshot(
      bigtable::ClusterId const& cluster_id,
      bigtable::SnapshotId const& snapshot_id);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

### LINKED ISSUE #1951: Return Status from bigtable::TableAdmin::DeleteSnapshot
Rather than throwing on error, return Status. The signature should look like:

```c++
  Status DeleteSnapshot(bigtable::ClusterId const& cluster_id,
                      bigtable::SnapshotId const& snapshot_id);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

### LINKED ISSUE #1952: Return StatusOr from bigtable::TableAdmin::ListSnapshots
Rather than throwing on error, return StatusOr. The signature should look like the following:

```c++
  template <template <typename...> class Collection = std::vector>
  StatusOr<Collection<::google::bigtable::admin::v2::Snapshot>> ListSnapshots(
      bigtable::ClusterId cluster_id = bigtable::ClusterId("-"));
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

### LINKED ISSUE #1954: Use iterators in Bigtable List* functions?
Since we are changing the Bigtable functions that return collections (typically `List*`), we should think about whether they should return things that be iterated on, but only download a few elements at a time vs. downloading all the elements.

We currently return a vector / collection because we "know" the populations will be small, even though the underlying API uses pagination. For consistency with other APIs (think `ListObjects` in GCS, or `ReadRows` in Bigtable) we should consider changing all of these APIs to return iterator-like things.

### PR DESCRIPTION
**Pull request by dopiera**
This fixes #1943
This fixes #1944
This fixes #1945
This fixes #1946 
This fixes #1947
This fixes #1948
This fixes #1949
This fixes #1950
This fixes #1951
This fixes #1952

In #1948 (`CheckConsistency`) I used `StatusOr<bool>` because I anticipate we remove it. This is simply the least effort.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/1958)

### CODE REVIEW

**Comment by dopiera** [comment]
The test failure is unrelated.

**Comment by coryan** [comment]
For what is worth, the build problem should be fixed at `master`, consider rebasing.

File: google/cloud/bigtable/examples/table_admin_snippets.cc [hunk 1]
```diff
@@ -156,8 +164,13 @@ void ModifyTable(google::cloud::bigtable::TableAdmin admin, int argc,
                         google::cloud::bigtable::GcRule::MaxAge(
                             std::chrono::hours(72))))});
 
+    if (!schema) {
+      std::cerr << "ModifyColumnFamilies failed: " << schema.status()
```
Comment (devjgm) [inline google/cloud/bigtable/examples/table_admin_snippets.cc]: We recently submitted https://github.com/googleapis/google-cloud-cpp/pull/1957 to the GCS library. The intent was to minimize the error handling noise in the sample code. So rather than a (potentially wrapping) cerr statement followed by a return, we simply `throw` the status wrapped in a runtime_error.

I'm thinking we probably want to do the same in the Bigtable library too, but I'm going to summon @frankyn for his opinion.

File: google/cloud/bigtable/examples/table_admin_snippets.cc [hunk 2]
```diff
@@ -259,8 +288,14 @@ void GenerateConsistencyToken(google::cloud::bigtable::TableAdmin admin,
...
   [](google::cloud::bigtable::TableAdmin admin, std::string table_id) {
-    std::string token = admin.GenerateConsistencyToken(table_id);
-    std::cout << std::endl << "generated token is : " << token << std::endl;
+    auto token = admin.GenerateConsistencyToken(table_id);
+    if (!token) {
+      std::cerr << "GenerateConsistencyToken failed: " << token.status()
+                << std::endl;
+      return;
+    }
+    std::cout << std::endl
```
Comment (devjgm) [inline google/cloud/bigtable/examples/table_admin_snippets.cc]: I realize this leading newline was here before your change, but is it needed? Do you know why this is here? I ask because I'm not seeing this in the other examples.

File: google/cloud/bigtable/internal/table_admin.cc [hunk 3]
```diff
@@ -235,16 +235,15 @@ void TableAdmin::DeleteSnapshot(bigtable::ClusterId const& cluster_id,
       &AdminClient::DeleteSnapshot, request, "DeleteSnapshot", status);
 }
 
-void TableAdmin::ListSnapshotsImpl(
-    bigtable::ClusterId const& cluster_id,
-    std::function<void(google::bigtable::admin::v2::Snapshot)> const& inserter,
-    grpc::Status& status) {
+std::vector<google::bigtable::admin::v2::Snapshot> TableAdmin::ListSnapshots(
+    grpc::Status& status, bigtable::ClusterId const& cluster_id) {
```
Comment (devjgm) [inline google/cloud/bigtable/internal/table_admin.cc]: out-params (and in-out params) are typically listed last in the function signature, according to our style guide. So perhaps move `status` to be the last parameter.

File: google/cloud/bigtable/internal/table_admin.cc [hunk 4]
```diff
@@ -260,11 +259,11 @@ void TableAdmin::ListSnapshotsImpl(
...
     }
 
-    for (auto& x : *response.mutable_snapshots()) {
-      inserter(x);
-    }
+    auto& snapshots = *response.mutable_snapshots();
+    std::move(snapshots.begin(), snapshots.end(), std::back_inserter(result));
     page_token = std::move(*response.mutable_next_page_token());
   } while (!page_token.empty());
+  return result;
```
Comment (devjgm) [inline google/cloud/bigtable/internal/table_admin.cc]: It's a little funny that this may return an empty vector (or even a non-empty vector?) even if the out-status is non-OK. It's up to the caller to ignore the returned vector based on the value of status. This seems like a case where we'd want to return `StatusOr<vector<Foo>>` which would cover both cases. 

Now I'm new to this bigtable library, so I'm not sure if we want to insert StatusOr in this internal interface... but I'm thinking maybe we do?  Thoughts?

File: google/cloud/bigtable/table_admin_test.cc [hunk 5]
```diff
@@ -614,7 +576,7 @@ TEST_F(TableAdminTest, DropAllRows) {
   EXPECT_CALL(*client_, DropRowRange(_, _, _)).WillOnce(Invoke(mock));
 
   // After all the setup, make the actual call we want to test.
-  tested.DropAllRows("the-table");
+  EXPECT_TRUE(tested.DropAllRows("the-table").ok());
```
Comment (devjgm) [inline google/cloud/bigtable/table_admin_test.cc]: If this assertion fails, there won't be anything very useful in the logs since the `Status` object is not logged. In other cases I think we've been doing something like:

```c++
auto x = foo.DoFoo();
EXPECT_TRUE(x.ok()) << x;
```

Yes, that's a bit of a PITA to do in all cases. I filed https://github.com/googleapis/google-cloud-cpp/issues/1980 to create an ASSERT_OK() that will do the Right Thing for StatusOr and Status objects, but it doesn't exist yet.

File: google/cloud/bigtable/examples/bigtable_samples.cc [hunk 6]
```diff
@@ -53,11 +53,15 @@ void RunTableOperations(google::cloud::bigtable::TableAdmin admin,
   std::cout << "Get table: " << std::endl;
   auto table =
       admin.GetTable(table_id, google::bigtable::admin::v2::Table::FULL);
-  std::cout << table.name() << "\n";
-  std::cout << "Table name : " << table.name() << std::endl;
+  if (!table) {
+    std::cerr << "GetTable failed: " << table.status() << std::endl;
+    return;
+  }
+  std::cout << table->name() << "\n";
```
[the remark this answers is not in the document]
Comment (devjgm) [reply google/cloud/bigtable/examples/bigtable_samples.cc]: fyi, I fixed/closed #1978, so please s/std::endl/"\n"/g in this PR.

File: google/cloud/bigtable/internal/table_admin.cc (hunk 4 above)
Comment (rsimion) [reply google/cloud/bigtable/internal/table_admin.cc]: Sorry to jump in.
@coryan  asked me not to change the internal interface yet. I am working on #1965 and
I am using this issue as an example for my changes.

Comment (coryan) [reply google/cloud/bigtable/internal/table_admin.cc]: @rsimion Did I?  I probably did, but it all depends on context.  @devjgm introducing `StatusOr<>` here is probably Okay, in any case this class (`bigtable::noex::TableAdmin`) should be removed soon after this PR is merged because then `bigtable::TableAdmin` would have identical functionality and a cleaner interface.

File: google/cloud/bigtable/table_admin_test.cc (hunk 5 above)
Comment (dopiera) [reply google/cloud/bigtable/table_admin_test.cc]: Done with `ASSERT_STATUS_OK`.

**Comment by dopiera** [comment]
Friendly ping. Is there anything else I should fix here?

**Comment by coryan** [comment]
@dopiera There are conflicts in this PR, do you mind resolving them so we can merge?
