### PR TITLE
test: deflake background_threads_impl_test

### LINKED ISSUE #4469: [Flake] BackgroundThreadsImpl times out under load
Seems like another case of a timeout that is too short for an overloaded build server:

https://source.cloud.google.com/results/invocations/bc96e94b-61f9-4e1a-87dd-d115c023f2c0/targets

```
FAIL: //google/cloud:internal_background_threads_impl_test (see C:/b/rvommcsc/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/x64_windows-opt/testlogs/google/cloud/internal_background_threads_impl_test/test.log)
INFO: From Testing //google/cloud:internal_background_threads_impl_test:
==================== Test output for //google/cloud:internal_background_threads_impl_test:
Running main() from gmock_main.cc
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from CustomerSuppliedBackgroundThreads
[ RUN      ] CustomerSuppliedBackgroundThreads.LifecycleNoShutdown
google/cloud/internal/background_threads_impl_test.cc(45): error: Expected equality of these values:
  std::future_status::ready
    Which is: 4-byte object <00-00 00-00>
  expired.wait_for(ms(500))
    Which is: 4-byte object <01-00 00-00>
[  FAILED  ] CustomerSuppliedBackgroundThreads.LifecycleNoShutdown (1296 ms)
[ RUN      ] CustomerSuppliedBackgroundThreads.SharesCompletionQueue
[       OK ] CustomerSuppliedBackgroundThreads.SharesCompletionQueue (326 ms)
[----------] 2 tests from CustomerSuppliedBackgroundThreads (1622 ms total)

[----------] 1 test from AutomaticallyCreatedBackgroundThreads
[ RUN      ] AutomaticallyCreatedBackgroundThreads.IsActive
[       OK ] AutomaticallyCreatedBackgroundThreads.IsActive (2 ms)
[----------] 1 test from AutomaticallyCreatedBackgroundThreads (3 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test suites ran. (1625 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CustomerSuppliedBackgroundThreads.LifecycleNoShutdown

 1 FAILED TEST
================================================================================
```

### PR DESCRIPTION
**Pull request by coryan**
Before this PR the tests would (a) pass without problems when not under
load, (b) when under load (a second build running simultaneously) it
would fail about 80 times out of 10,000. After this change the test
passed 20,000 times under load and another 20,000 times without load.
The worst case running time is about 11 seconds, which suggests to me
the shorter 500ms timeouts are not a good tradeoff as they cost some
flakiness in our builds.

Fixes #4469 

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4470)

### CODE REVIEW

File: google/cloud/internal/background_threads_impl_test.cc [hunk 1]
```diff
@@ -1,4 +1,5 @@
 // Copyright 2019 Google LLC
+// Copyright 2019 Google LLC
```
Comment (devbww) [inline google/cloud/internal/background_threads_impl_test.cc:2]: Oops?

Comment (coryan) [reply google/cloud/internal/background_threads_impl_test.cc]: Indeed, fixed.
