### PR TITLE
test(spanner): fix driver for slow samples

### LINKED ISSUE #6020: Spanner sample is using the wrong instance + database combo
The build failed with:

```
Running spanner_create_database sample
Created database [projects/cloud-cpp-testing-resources/instances/temporary-instance-2021-03-11-pyi6o59xxeqz3m0l0s6lxcuhxmtmsbjf4z/databases/db-2021-03-11-ivi266nt-n3ddkl2]

Running spanner_create_backup sample
Permanent error in CreateSessionsSync: Database not found: projects/cloud-cpp-testing-resources/instances/test-instance-6/databases/db-2021-03-11-ivi266nt-n3ddkl2 [NOT_FOUND]
```

Note that the database is created in `temporary-instance-2021-03-11-pyi6o59xxeqz3m0l0s6lxcuhxmtmsbjf4z` and the failure is on `test-instance-6`.

https://source.cloud.google.com/results/invocations/a5961d35-049b-4b36-8aba-402f1dfb5b64

This is from here:

https://github.com/googleapis/google-cloud-cpp/blob/ad0bfd14e1531032c286101bcdb5e76338bedc1b/google/cloud/spanner/samples/samples.cc#L3231-L3241

### PR DESCRIPTION
**Pull request by coryan**
It was using the wrong instance + database id combination for one of the
tests. I did some refactoring because it was hard to see how these tests
worked or to reason about what instances / databases where created when.

Fixes #6020

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6021)

### CODE REVIEW

File: google/cloud/spanner/samples/samples.cc [hunk 1]
```diff
@@ -3142,6 +3147,92 @@ void RunAll(bool emulator) {
       run_slow_integration_tests.find("backup") != std::string::npos;
   auto const run_slow_instance_tests =
       run_slow_integration_tests.find("instance") != std::string::npos;
+
+  if (!run_slow_instance_tests) return;
```
Comment (devbww) [inline google/cloud/spanner/samples/samples.cc:3151]: It is a shame that `GOOGLE_CLOUD_CPP_SPANNER_SLOW_INTEGRATION_TESTS=backup` is meaningless (you need to say `instance,backup`).  But, that's just an observation about the status quo ... nothing to do here.

**Review by devbww — APPROVED** [review]

File: google/cloud/spanner/samples/samples.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/spanner/samples/samples.cc:3151]: Ack.
