### PR TITLE
fix(storage)!: incorrect type in OLM condition

### LINKED ISSUE #4592: createdBefore has `date` type, not `datetime`
From the documentation:

```
A date in RFC 3339 format with only the date part (for instance, "2013-01-15"). This condition is satisfied when an object is created before midnight of the specified date in UTC.
```

https://cloud.google.com/storage/docs/json_api/v1/buckets

We are using the full RFC3339 format.

### PR DESCRIPTION
**Pull request by coryan**
**BREAKING CHANGE**: changed the `created_before` field in
`LifecycleRuleCondition` from a time point to a date. The service
rejects timestamps, it only accepts dates in YYYY-mm-dd format. We
considered trying to keep the C++ type the same and fixing the
conversions to the underlying protocol, but (a) this was confusing to
any users, and (b) we do not expect anybody was using this field because
it simply did not work before.

Fixes #4592

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4597)

### CODE REVIEW

File: google/cloud/storage/lifecycle_rule.cc [hunk 1]
```diff
@@ -62,6 +63,17 @@ LifecycleRuleAction LifecycleRule::SetStorageClass(std::string storage_class) {
   return LifecycleRuleAction{"SetStorageClass", std::move(storage_class)};
 }
 
+LifecycleRuleCondition LifecycleRule::CreatedBefore(std::string const& date) {
```
Comment (devjgm) [inline google/cloud/storage/lifecycle_rule.cc:66]: Q: Do you think it's necessary to have this `CreatedBefore` overload that takes a string? I know we have it today, and users may be passing full time strings, which would fail to parse as a date here and it would throw/crash. This overload is avoiding a build break, but instead there might be a runtime exception/crash.

Since this PR is already a breaking change, I'm wondering if maybe we want to get rid of this overload taking a string and require the caller to pass us a `CivilDay`, which will push any string-to-date error handling onto the caller.

Just a thought. WDYT?

Comment (coryan) [reply google/cloud/storage/lifecycle_rule.cc:66]: I was about to push the commit to remove these.

Comment (devjgm) [reply google/cloud/storage/lifecycle_rule.cc:66]: I was waiting for this removal, but let me know if you'd like approval before that, or want to do that in a separate PR.

Comment (coryan) [reply google/cloud/storage/lifecycle_rule.cc]: Sorry for the delay, I had to rebase and fix the API baseline.

**Comment by coryan** [comment]
PTAL
