### PR TITLE
fix: handle completed uploads in UploadChunk

### LINKED ISSUE #3342: GCS Resumable Uploads erroneously ABORTED
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

Yes.

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

v1.8.0

### What were you trying to do?

Upload objects to GCS via Resumable Upload.

### What did you expect to see?

Objects are uploaded successfully.

### What did you see instead?

Uploads of objects that are exact multiples of the upload chunk size are erroneously `ABORTED` and must be retried.

### Anything else you would like us to know?

When uploading objects of sizes 2MiB, 3MiB, and 4MiB with an upload chunk size of 2MiB, the final chunk upload of only the 4MiB object results in the client library returning:
+ `ABORTED`
+ "Could not continue upload stream. GCS requested byte 0 which has already been uploaded."

The actual response received by the client library is a HTTP 200, which indicates that [the resumable upload is complete](https://cloud.google.com/storage/docs/performing-resumable-uploads#upload-file).

This error message originates from [this PR](https://github.com/googleapis/google-cloud-cpp/pull/3283). Perhaps there is a boundary edge-case which causes this error to be erroneously returned?

### PR DESCRIPTION
**Pull request by coryan**
Applications can provide the `X-Upload-Content-Length` header in their
resumable uploads. This let's GCS know how many bytes to expect, and GCS
completes an upload as soon as that many bytes arrive. In this case the
response does not have a `Range:` header indicating the last committed
byte, and these responses must be handled differently.

Fixes #3342

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/3348)

### CODE REVIEW

File: google/cloud/storage/internal/logging_resumable_upload_session.cc [hunk 1]
```diff
@@ -41,47 +41,47 @@ LoggingResumableUploadSession::UploadFinalChunk(std::string const& buffer,
...
   auto const& response = session_->session_id();
-  GCP_LOG(INFO) << __func__ << " >> " << response;
+  GCP_LOG(INFO) << __func__ << "() >> " << response;
   return response;
 }
 
 StatusOr<ResumableUploadResponse> const&
 LoggingResumableUploadSession::last_response() const {
-  GCP_LOG(INFO) << __func__ << " << ()";
+  GCP_LOG(INFO) << __func__ << "() << {}}";
```
Comment (devbww) [inline google/cloud/storage/internal/logging_resumable_upload_session.cc]: s/}}/}/?

File: google/cloud/storage/tests/object_resumable_write_integration_test.cc [hunk 2]
```diff
@@ -252,6 +252,116 @@ TEST_F(ObjectResumableWriteIntegrationTest, StreamingWriteSlow) {
...
+  ASSERT_STATUS_OK(options);
+  Client client(options->SetUploadBufferSize(chunk_size));
+
+  std::string bucket_name = flag_bucket_name;
+
+  auto const chunk = MakeRandomData(chunk_size);
+
+  for (auto const desired_size : {2 * MiB, 3 * MiB, 4 * MiB}) {
+    auto object_name = MakeRandomObjectName();
+    SCOPED_TRACE("Testing with desired_size = " + std::to_string(desired_size) +
```
Comment (devbww) [inline google/cloud/storage/tests/object_resumable_write_integration_test.cc]: s/ = /=/ perhaps?

File: google/cloud/storage/tests/object_resumable_write_integration_test.cc [hunk 3]
```diff
@@ -252,6 +252,116 @@ TEST_F(ObjectResumableWriteIntegrationTest, StreamingWriteSlow) {
...
+        CustomHeader("X-Upload-Content-Length", std::to_string(desired_size)));
+    auto offset = 0L;
+    while (offset < desired_size) {
+      auto const n = (std::min)(desired_size - offset, chunk_size);
+      os.write(chunk.data(), n);
+      ASSERT_FALSE(os.bad());
+      offset += n;
+    }
+
+    // This operation should fail because the object already exists.
```
Comment (devbww) [inline google/cloud/storage/tests/object_resumable_write_integration_test.cc]: Q. Which part of the following indicates the failure?  Indeed, why should the random object exist?

Comment (coryan) [reply google/cloud/storage/tests/object_resumable_write_integration_test.cc]: That was a cut&paste error, fixed here and elsewhere.

File: google/cloud/storage/tests/object_resumable_write_integration_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/tests/object_resumable_write_integration_test.cc]: Better, thanks.

File: google/cloud/storage/internal/logging_resumable_upload_session.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/logging_resumable_upload_session.cc]: Fixed.
