### PR TITLE
fix(storage): cleanup interrupted downloads

### LINKED ISSUE #7051: CurlRequest::MakeRequestImpl could crash when SetOption for CURLOPT_BUFFERSIZE
**Does this issue affect the google-cloud-cpp project?**
If the problem is with the Google Cloud service exposed by the `google-cloud-cpp` libraries instead of the client libraries themselves, you may consider opening a support request instead. The `google-cloud-cpp` developers cannot help you troubleshoot problems with the service itself.
Yes.

**What component of `google-cloud-cpp` is this related to?**
For example, is this related to bigtable (i.e., something in `google/cloud/bigtable`), or GCS (i.e., something in `google/cloud/storage`)?
google/cloud/storage

**Describe the bug**
Curl lib setopt.c checks data->state.buffer and return CURLE_BAD_FUNCTION_ARGUMENT(https://github.com/curl/curl/pull/5842/files).
CurlRequestBuilder uses handle_ from a PooledCurlHandleFactory that reuses handle.
The handle could still have data->state.buffer set and would cause runtime error when
CurlRequest::MakeRequestImpl is called to SetOption for CURLOPT_BUFFERSIZE.

**To Reproduce**
1. Call function 'Curl::Client::CreateResumableSessionGeneric'
2. See runtime error.

**Expected behavior**
No runtime error.

**Operating system:**
If you are using a Linux distribution please include the name and version of the distribution too.

**What compiler and version are you using?**
Please include the output of `g++ -v` or `clang++ -v` or the equivalent command-line flag.

**What version of `google-cloud-cpp` are you using?**
Please include the output from `git rev-parse HEAD` if you are compiling from source, or the version number from the applicable `google/cloud/*/version.h` file.

**Additional context**
In EasyPerform -> easy_perform in easy.c either easy_events or easy_transfer would be called to initiate a transfer and possibly initialize data->state.buffer. In curl_multi_remove_handle, the multi_done step would call Curl_safefree for
data->state.buffer. So not sure why data->state.buffer would be set.

### PR DESCRIPTION
**Pull request by coryan**
Downloads can be interrupted by the application. Sometimes this results
in incomplete cleanup of the handle, which when reused would start
failing some `curl_easy_setopt()` calls.

Fixes #7051

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7064)

### CODE REVIEW

File: google/cloud/storage/tests/curl_download_request_integration_test.cc [hunk 1]
```diff
@@ -72,6 +74,65 @@ TEST(CurlDownloadRequestTest, SimpleStream) {
   EXPECT_EQ(kDownloadedLines, count);
 }
 
+// Run one attempt of the Regression7501 test. This is wrapped in a retry loop,
+// as integration tests flake due to unrelated (and unavoidable) problems, e.g.,
+// trying to setup connections.
+Status AttemptRegression7501() {
```
Comment (k7z45) [inline google/cloud/storage/tests/curl_download_request_integration_test.cc:80]: Do you mean 7051 vs. 7501?

File: google/cloud/storage/tests/curl_download_request_integration_test.cc [hunk 2]
```diff
@@ -72,6 +74,65 @@ TEST(CurlDownloadRequestTest, SimpleStream) {
...
+  // Download the maximum number of lines supported by httpbin.org
+  auto constexpr kDownloadedLines = 100;
+  auto constexpr kTestPoolSize = 32;
```
Comment (k7z45) [inline google/cloud/storage/tests/curl_download_request_integration_test.cc:83]: So this test is making the assumption that the same handle is used across multiple download requests. If so, would you like to assert that?

File: google/cloud/storage/tests/curl_download_request_integration_test.cc [hunk 3]
```diff
@@ -72,6 +74,65 @@ TEST(CurlDownloadRequestTest, SimpleStream) {
...
+
+  {
+    auto r_partial_close = make_download();
+    auto read = r_partial_close.Read(buffer, kBufferSize);
+    if (!read) return std::move(read).status();
+    auto close = r_partial_close.Close();
+    if (!close) return std::move(close).status();
+  }
+
+  auto r_full = make_download();
```
Comment (k7z45) [inline google/cloud/storage/tests/curl_download_request_integration_test.cc:111]: Do you need another no close read before the full read?

Comment (coryan) [reply google/cloud/storage/tests/curl_download_request_integration_test.cc:111]: No, I want to check that a handle where (a) not all the data is downloaded, and (b) you do call `Close()`, is usable.

File: google/cloud/storage/tests/curl_download_request_integration_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/tests/curl_download_request_integration_test.cc:83]: Done.  But I would have been happy to just test "the factory returns a usable handle".  If the handle is usable because it is brand new, or because it was completely cleaned up then 🤷 .

File: google/cloud/storage/tests/curl_download_request_integration_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/tests/curl_download_request_integration_test.cc]: Fixed.

**Review by devjgm — APPROVED** [review]
