### PR TITLE
fix(generator): handle empty method signatures

### LINKED ISSUE #7814: Generator needs to handle empty method signatures
For some reason, this exists:
https://github.com/googleapis/googleapis/blob/1236b08b701363015cbc876a850b60a061f23bb3/google/cloud/billing/v1/cloud_billing.proto#L55

Generator currently crashes because the `parameter_descriptor` is null in this case: https://github.com/googleapis/google-cloud-cpp/blob/a36bcfcb5e80ff9bc4ed9111fc18b4c89dd1d02e/generator/internal/descriptor_utils.cc#L186-L188

### PR DESCRIPTION
**Pull request by dbolduc**
Fixes #7814 

If we are given an empty parameter list, generate a client method that only takes `Options`.

I tried to break the change up into useful commits for the reviewer. They are:
1. logic changes
2. output for the generated client code
3. all other generated code (noise)
4. update a mock, which I forgot to do in the first commit.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7825)

### CODE REVIEW

File: generator/integration_tests/generator_integration_test.cc [hunk 1]
```diff
@@ -97,9 +97,7 @@ class GeneratorIntegrationTest : public testing::TestWithParam<std::string> {
                           "Codegen C++ Generator");
 
     product_path_ = "generator/integration_tests/golden/";
-    // The golden files were last generated on 2021, update next time you
-    // re-generate said files.
-    copyright_year_ = "2021";
+    copyright_year_ = CurrentCopyrightYear();
```
Comment (coryan) [inline generator/integration_tests/generator_integration_test.cc:100]: I would rather you did 2022, that way we will not have the same breaks on 2023-01-01 we had in 2022-01-01.

Frankly, I would rather we pinned these to a specific year, but since I don't know how to do that ...

File: generator/integration_tests/test.proto [hunk 2]
```diff
@@ -63,6 +63,14 @@ service GoldenThingAdmin {
     option (google.api.method_signature) = "parent";
   }
 
+  // Does Nothing.
```
Comment (coryan) [inline generator/integration_tests/test.proto:66]: if this was the las method you would have fewer spurious changes due to line numbers...  Just saying.

**Review by coryan — CHANGES_REQUESTED** [review]

File: generator/integration_tests/generator_integration_test.cc (hunk 1 above)
Comment (dbolduc) [reply generator/integration_tests/generator_integration_test.cc]: Done.

File: generator/integration_tests/test.proto (hunk 2 above)
Comment (dbolduc) [reply generator/integration_tests/test.proto]: You're right. I moved it into the last `service`.
(less overall changes, but half the line numbers changed in the latest commit 🤷‍♂️)
