### PR TITLE
fix(storage)!: handle missing range header in uploads

### LINKED ISSUE #7835: Incorrect handling of resumable upload responses without a range header
The client library treats 308 responses as an unrecoverable error:

https://github.com/googleapis/google-cloud-cpp/blob/49b5cc2423bbbb6b763f07dccf8b9aee3a04524c/google/cloud/storage/internal/retry_resumable_upload_session.cc#L76

which can be triggered from here:

https://github.com/googleapis/google-cloud-cpp/blob/49b5cc2423bbbb6b763f07dccf8b9aee3a04524c/google/cloud/storage/internal/resumable_upload_session.cc#L50-L57

However the spec allows for an empty range header:

> If Cloud Storage has not yet persisted any bytes, the 308 response does **not have a Range header**. In this case, you should start your upload from the beginning.

https://cloud.google.com/storage/docs/performing-resumable-uploads

### PR DESCRIPTION
**Pull request by coryan**
Resumable upload responses use the `Range` header to report how many
bytes were committed. Sometimes, maybe once every few million uploads,
the header is missing. This indicates that nothing was committed.
The library was treating this as a permanent error. The correct behavior
is to query the status of the upload and try again.

Fixes #7835

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877)

### CODE REVIEW

File: google/cloud/storage/internal/retry_resumable_upload_session.cc [hunk 1]
```diff
@@ -57,112 +57,164 @@ StatusOr<ResumableUploadResponse> RetryResumableUploadSession::UploadFinalChunk(
...
+      auto delay = backoff_policy->OnCompletion();
+      std::this_thread::sleep_for(delay);
+      operation = &reset;
       continue;
     }
-    last_status = std::move(result).status();
-    if (!retry_policy->OnFailure(last_status)) {
-      return ReturnError(std::move(last_status), *retry_policy, __func__);
+
+    // Sometimes the upload completes in a regular `UploadChunk()` or event a
```
Comment (devbww) [inline google/cloud/storage/internal/retry_resumable_upload_session.cc:155]: "or event a"?

File: google/cloud/storage/internal/retry_resumable_upload_session.cc [hunk 2]
```diff
@@ -57,112 +57,164 @@ StatusOr<ResumableUploadResponse> RetryResumableUploadSession::UploadFinalChunk(
...
+    // `ResetSession()` call. For example, the server can detect a completed
+    // upload "early" if the application includes the X-Upload-Content-Length`
+    // header.
+    if (result->upload_state == ResumableUploadResponse::kDone) return result;
+
+    // This indicates that the response was missing a `Range:` header, or that
+    // the range header was in the wrong format, either way, treat that as a
```
Comment (devbww) [inline google/cloud/storage/internal/retry_resumable_upload_session.cc:162]: s/, either way/. Either way/

File: google/cloud/storage/internal/retry_resumable_upload_session.cc [hunk 3]
```diff
@@ -57,112 +57,164 @@ StatusOr<ResumableUploadResponse> RetryResumableUploadSession::UploadFinalChunk(
...
+// Implements the retry loop for a resumable upload session.
+//
+// A description of resumable uploads can be found at:
+//     https://cloud.google.com/storage/docs/performing-resumable-uploads
+//
+// A description of the gRPC analog can be found in the proto file:
+//    https://github.com/googleapis/googleapis/blob/master/google/storage/v2/storage.proto
+//
+// Particularly the documentation for `WriteObject()`, `WriteObjectRequest`,
+// `StartResumablewrite()` and `QueryResumableWrite()`.
```
Comment (devbww) [inline google/cloud/storage/internal/retry_resumable_upload_session.cc:69]: Perhaps this would be better before the colon in the previous block.

File: google/cloud/storage/internal/retry_resumable_upload_session.cc [hunk 4]
```diff
@@ -57,112 +57,164 @@ StatusOr<ResumableUploadResponse> RetryResumableUploadSession::UploadFinalChunk(
...
+//
+// At a high level one starts a resumable upload by creating a "session". These
+// sessions are persistent, they survive disconnections from the service, one
```
Comment (devbww) [inline google/cloud/storage/internal/retry_resumable_upload_session.cc:72]: Perhaps ...

_These sessions are persistent (they survive disconnections from the service).  One can even ..._

File: google/cloud/storage/internal/retry_resumable_upload_session.cc [hunk 5]
```diff
@@ -57,112 +57,164 @@ StatusOr<ResumableUploadResponse> RetryResumableUploadSession::UploadFinalChunk(
...
+// can even resume uploads after shutting down and restarting an application.
+// Their current state can be queried using a simple RPC (or a PUT request
+// without payload).
+//
+// Resumable uploads make progress by sending "chunks", a single PUT request in
```
Comment (devbww) [inline google/cloud/storage/internal/retry_resumable_upload_session.cc:77]: Perhaps ...

_Resumable uploads make progress by sending "chunks", either a ..., or a ..._

if I understand correctly.

File: google/cloud/storage/internal/retry_resumable_upload_session_test.cc [hunk 6]
```diff
@@ -597,67 +557,163 @@ TEST_F(RetryResumableUploadSessionTest, HandleTransientPartialFailures) {
...
+  ::testing::InSequence sequence;
+  // Simulate a successful upload to have the number of committed bytes be
+  // non-zero.
+  EXPECT_CALL(*mock, UploadChunk).WillOnce([&](ConstBufferSequence const&) {
+    return make_status_or(ResumableUploadResponse{
+        "", ResumableUploadResponse::kInProgress, quantum, {}, {}});
+  });
+
+  // Simulate an upload that "succeeds", but returns a missing value for the
+  // committed size, this should trigger a reset.
```
Comment (devbww) [inline google/cloud/storage/internal/retry_resumable_upload_session_test.cc:588]: s/size, this/size. This/

File: google/cloud/storage/internal/retry_resumable_upload_session.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_resumable_upload_session.cc]: Fixed I hope.

File: google/cloud/storage/internal/retry_resumable_upload_session.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_resumable_upload_session.cc]: Fixed.

File: google/cloud/storage/internal/retry_resumable_upload_session.cc (hunk 3 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_resumable_upload_session.cc]: Done. And thanks.

File: google/cloud/storage/internal/retry_resumable_upload_session.cc (hunk 4 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_resumable_upload_session.cc]: Fixed.

File: google/cloud/storage/internal/retry_resumable_upload_session.cc (hunk 5 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_resumable_upload_session.cc]: Thanks.

File: google/cloud/storage/internal/retry_resumable_upload_session_test.cc (hunk 6 above)
Comment (coryan) [reply google/cloud/storage/internal/retry_resumable_upload_session_test.cc]: Fixed.

**Comment by coryan** [comment]
PTAL.

**Review by devbww — APPROVED** [review]

**Comment by Jseph** [comment]
___
*[google/cloud/storage/internal/retry_resumable_upload_session.cc, line 140 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877#-MtAKYAz5IBP6C2b6OND:-MtAKYAz5IBP6C2b6ONE:b-3tfc4j) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45022d3a3b2f377acc9cb6d61bc85adf3567df7/google/cloud/storage/internal/retry_resumable_upload_session.cc#L140)):*
> ```cpp
>     auto const pre_operation_committed_size = committed_size_;
>     auto result = (*operation)(buffers);
>     AppendDebug("upload", static_cast<std::uint64_t>(result.status().code()));
> ```

This is potentially misleading because this may be the result of an upload or a reset.

**Comment by Jseph** [comment]
___
*[google/cloud/storage/internal/retry_resumable_upload_session.cc, line 164 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877#-MtAKvfI7ritFBpmL7Cy:-MtAKvfI7ritFBpmL7Cz:b-wr5223) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45022d3a3b2f377acc9cb6d61bc85adf3567df7/google/cloud/storage/internal/retry_resumable_upload_session.cc#L164)):*
> ```cpp
>     // This indicates that the response was missing a `Range:` header, or that
>     // the range header was in the wrong format. Either way, treat that as a
>     // (transient) failure and start over.
> ```

Nit: The combination of `start over` and the reset call below led me to believe that the upload is being restarted from the beginning. This isn't the case, the upload session is just querying GCS for its current state.



_Code quote:_
```cpp
start over
```

**Comment by coryan** [comment]
___
*[google/cloud/storage/internal/retry_resumable_upload_session.cc, line 140 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877#-MtAKYAz5IBP6C2b6OND:-MtALl0FCeJXs969aWQ4:bmq8xca) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45022d3a3b2f377acc9cb6d61bc85adf3567df7/google/cloud/storage/internal/retry_resumable_upload_session.cc#L140)):*
<details><summary><i>Previously, Jseph wrote…</i></summary><blockquote>

This is potentially misleading because this may be the result of an upload or a reset.
</blockquote></details>

True.  I was (and still am) tempted to remove these debugging statements.  They are a drag and they served their purpose.  Thoughts?

**Comment by coryan** [comment]
___
*[google/cloud/storage/internal/retry_resumable_upload_session.cc, line 164 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877#-MtAKvfI7ritFBpmL7Cy:-MtAM2x92nNkuBdSq05I:b-c0m60c) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45022d3a3b2f377acc9cb6d61bc85adf3567df7/google/cloud/storage/internal/retry_resumable_upload_session.cc#L164)):*
<details><summary><i>Previously, Jseph wrote…</i></summary><blockquote>

Nit: The combination of `start over` and the reset call below led me to believe that the upload is being restarted from the beginning. This isn't the case, the upload session is just querying GCS for its current state.
</blockquote></details>

Will send a PR to clarify that.

**Comment by Jseph** [comment]
___
*[google/cloud/storage/internal/retry_resumable_upload_session.cc, line 192 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877#-MtAMNSUEMZ2pjCFjR82:-MtAMNSUEMZ2pjCFjR83:b7mu884) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45022d3a3b2f377acc9cb6d61bc85adf3567df7/google/cloud/storage/internal/retry_resumable_upload_session.cc#L192)):*
> ```cpp
> 
>     // On a full write we can return immediately.
>     if (written == size) return result;
> ```

It's also possible in the case of racing processes uploading to the same session that `written > size` in which case I think the thing to do is also return result?  That should cause the object_write_streambuf to go into a bad state.  Otherwise I think you get stuck in a loop trying to do an upload with 0 bytes until the retries are exhausted.



_Code quote:_
```cpp
if (written == size) return result;
```

**Comment by Jseph** [comment]
___
*[google/cloud/storage/internal/retry_resumable_upload_session.cc, line 140 at r2](https://reviewable.io/reviews/googleapis/google-cloud-cpp/7877#-MtAKYAz5IBP6C2b6OND:-MtAWVIVBsZ_DZPjhC03:b-hy8kp7) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/e45022d3a3b2f377acc9cb6d61bc85adf3567df7/google/cloud/storage/internal/retry_resumable_upload_session.cc#L140)):*
<details><summary><i>Previously, coryan (Carlos O'Ryan) wrote…</i></summary><blockquote>

True.  I was (and still am) tempted to remove these debugging statements.  They are a drag and they served their purpose.  Thoughts?
</blockquote></details>

Yeah seems like the error code doesn't matter to the user (retries are successful) or they are returned anyway as the result of this function.
