### PR TITLE
fix(pubsub): deadlocks for cancel during session startup

### LINKED ISSUE #6053: [Flake] Pub/Sub samples timeout in test
https://source.cloud.google.com/results/invocations/29229a70-3153-456e-8e9e-f55f127bafad

```
7/7 Test #207: pubsub_samples ...............................***Timeout 1500.10 sec
```

### PR DESCRIPTION
**Pull request by coryan**
If an application canceled a session before the first `Write()` call
completes in the startup sequence.

Changed `pubsub/samples/samples.cc` to make it easier to troubleshoot
this problem, I am keeping the change because it feels generally useful.

Fixes #6053

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/6055)

### CODE REVIEW

File: google/cloud/pubsub/internal/streaming_subscription_batch_source.cc [hunk 1]
```diff
@@ -141,15 +141,21 @@ void StreamingSubscriptionBatchSource::OnInitialWrite(RetryLoopState const& rs,
...
+            [weak,
+             rs](future<
+                 absl::optional<google::pubsub::v1::StreamingPullResponse>>
+                     f) {
+              if (auto s = weak.lock())
+                s->OnInitialRead(std::move(rs), f.get());
+            });
+      });
+  // This is very rare, but if the session enters shutdown while the initial
+  // setup is in progress it can happen.
```
Comment (devbww) [inline google/cloud/pubsub/internal/streaming_subscription_batch_source.cc:157]: Perhaps "This is very rare, but it can happen if ...".

**Review by devbww — APPROVED** [review]

File: google/cloud/pubsub/internal/streaming_subscription_batch_source.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/pubsub/internal/streaming_subscription_batch_source.cc]: Done.
