### PR TITLE
making partial errors/last_status available to `ObjectWriteStream`

### LINKED ISSUE #2827: Make partial errors accessible in ObjectWriteStream.
When uploading objects it would be nice to be able to check for errors immediately, with some details about what failed, for example:

```C++
auto stream = client.WriteObject(...);

stream.write(...);
if (stream.bad()) {
    std::cerr << "Error writing to stream... status=" << stream.last_status();
}
```

The `.last_status()` function does not exist today, of course. We need something like it.

### PR DESCRIPTION
**Pull request by manish-qlogic**
`ObjectWriteStreamBuf` now offers `last_status` and this status can be used by `ObjectWriteStream` to determine partial errors. 

This fixes #2827.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2919)

### CODE REVIEW

File: google/cloud/storage/internal/object_streambuf.h [hunk 1]
```diff
@@ -146,6 +148,7 @@ class ObjectWriteStreambuf : public std::basic_streambuf<char> {
   HashValidator::Result hash_validator_result_;
 
   StatusOr<HttpResponse> last_response_;
+  Status last_status_;
```
Comment (devjgm) [inline google/cloud/storage/internal/object_streambuf.h]: Is there some relationship between last_response_ and last_statsus_? Like, if last_status_ is OK, then last_response_ is some 200 status? Or if last_response_ is not a 2xx HTTP status, then last_status_ is not OK?

It looks like that might be the case, other than in the constructor where last_response_ is initialized to a 400 HTTP status code, and last_status_ is initialized with OK.

I'm not suggesting any change here, just trying to understand this better since I'm not too familiar with this code.

File: google/cloud/storage/internal/object_streambuf_test.cc [hunk 2]
```diff
@@ -341,6 +341,95 @@ TEST(ObjectWriteStreambufTest, CreatedForFinalizedUpload) {
   EXPECT_EQ(close_result.value().payload, payload);
 }
 
+/// @test Verify that last error status is accessible for small payload.
+TEST(ObjectWriteStreambufTest, erroneousStream) {
```
Comment (devjgm) [inline google/cloud/storage/internal/object_streambuf_test.cc]: I think the casing of this test name should be `ErroneousStream`.

File: google/cloud/storage/internal/object_streambuf_test.cc [hunk 3]
```diff
@@ -341,6 +341,95 @@ TEST(ObjectWriteStreambufTest, CreatedForFinalizedUpload) {
...
+  auto mock = google::cloud::internal::make_unique<
+      testing::MockResumableUploadSession>();
+  EXPECT_CALL(*mock, done).WillRepeatedly(Return(false));
+
+  auto const quantum = UploadChunkRequest::kChunkSizeQuantum;
+  std::string const payload = "small test payload";
+
+  int count = 0;
+  EXPECT_CALL(*mock, UploadFinalChunk(_, _))
+      .WillOnce(Invoke([&](std::string const& p, std::uint64_t s) {
```
Comment (devjgm) [inline google/cloud/storage/internal/object_streambuf_test.cc]: `s` as the name for an integer may mislead people into thinking it's a string. How about `n`?

File: google/cloud/storage/internal/object_streambuf_test.cc [hunk 4]
```diff
@@ -341,6 +341,95 @@ TEST(ObjectWriteStreambufTest, CreatedForFinalizedUpload) {
...
+  auto response = streambuf.Close();
+
+  EXPECT_EQ(StatusCode::kInvalidArgument, response.status().code())
+      << ", status=" << response.status();
+  EXPECT_EQ(StatusCode::kInvalidArgument, streambuf.last_status().code())
+      << ", status=" << streambuf.last_status();
+}
+
+/// @test Verify that last error status is accessible for large payloads.
+TEST(ObjectWriteStreambufTest, errorInLargePayload) {
```
Comment (devjgm) [inline google/cloud/storage/internal/object_streambuf_test.cc]: Casing on the test name here too.

File: google/cloud/storage/object_stream.h [hunk 5]
```diff
@@ -343,6 +343,15 @@ class ObjectWriteStream : public std::basic_ostream<char> {
...
   void Suspend() &&;
 
+  /**
+   * Returns the status of partial errors.
+   *
+   * Application may write multiple times before closing the stream, this
+   * function gives the capability to find out status even before stream
+   * closure.
+   */
+  Status const& last_status() const { return buf_->last_status(); }
```
Comment (remyabel) [inline google/cloud/storage/object_stream.h]: Since this is part of the public API, `last_status()` may be confused to have a similar role to `ObjectReadStream`'s `status()`. Maybe this should document that `last_status()` has a relationship to `last_response` and signals different errors not already covered by `metadata()`.

File: google/cloud/storage/internal/object_streambuf.cc [hunk 6]
```diff
@@ -201,7 +201,8 @@ ObjectWriteStreambuf::ObjectWriteStreambuf(
     : upload_session_(std::move(upload_session)),
       max_buffer_size_(UploadChunkRequest::RoundUpToQuantum(max_buffer_size)),
       hash_validator_(std::move(hash_validator)),
-      last_response_{HttpResponse{400, {}, {}}} {
+      last_response_{HttpResponse{400, {}, {}}},
+      last_status_(Status()) {
```
[the remark this answers is not in the document]
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf.cc]: fixed.

File: google/cloud/storage/internal/object_streambuf_test.cc (hunk 2 above)
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf_test.cc]: fixed.

File: google/cloud/storage/object_stream.h (hunk 5 above)
Comment (remyabel) [reply google/cloud/storage/object_stream.h]: Alternatively, if `last_status()` overlaps with `metadata().status()` maybe this can just be renamed to `status()`?

File: google/cloud/storage/internal/object_streambuf_test.cc (hunk 3 above)
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf_test.cc]: Changed to n.

File: google/cloud/storage/internal/object_streambuf_test.cc (hunk 4 above)
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf_test.cc]: fixed.

File: google/cloud/storage/object_stream.h (hunk 5 above)
Comment (manish-qlogic) [reply google/cloud/storage/object_stream.h]: AFAIK, `metadata()` and `last_response` shows the final status where as `last_status()` can be used to find intermediate `UploadChunk` status or partial errors. Let me update comments for `last_status()`

File: google/cloud/storage/internal/object_streambuf.cc (hunk 6 above)
[the remark this answers is not in the document]
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf.cc]: `Kokoro ClangTidy` did not like this change, reverting it.

File: google/cloud/storage/object_stream.h (hunk 5 above)
Comment (remyabel) [reply google/cloud/storage/object_stream.h]: Thanks, makes sense. What do you think about renaming it to `latest_status` or something along those lines? But I'll defer to @coryan for that.

Nit: s/then/than/

File: google/cloud/storage/internal/object_streambuf.h (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/object_streambuf.h]: I think this is the key question.

For background, the application usually uses a `gcs::ObjectWriteStream`, and it performs error handling using IOStream errors, for example:

```C++
  gcs::ObjectWriteStream stream = client.WriteObject(....);
  ...
  ..
  ..
  .
  if (!stream.good()) {
   std::cerr << "Error, the last status was = " << stream.last_status(); // TODO: this is the point of this PR.
  }
```

I think we want that error checking code to always work, regardless of the previous operations (`.write()`, `.Close()`, `operator<<`, whatever). I think what we should do is change the code to be something like:

```
Status last_status() const {
  if (last_response_) {
    return Status();
  }
  return last_response_.status();
}
```

And always set `last_reponse_` when there is an error.

File: google/cloud/storage/internal/object_streambuf.cc [hunk 7]
```diff
@@ -332,7 +336,9 @@ StatusOr<HttpResponse> ObjectWriteStreambuf::Flush() {
   StatusOr<ResumableUploadResponse> result =
       upload_session_->UploadChunk(current_ios_buffer_);
   if (!result) {
-    // This was an unrecoverable error, time to signal an error.
+    // This was an unrecoverable error, time to store status and signal an
+    // error.
+    last_status_ = result.status();
```
Comment (coryan) [inline google/cloud/storage/internal/object_streambuf.cc]: See below, I think this should be `last_response_ = result.status()`.

File: google/cloud/storage/internal/object_streambuf.cc [hunk 8]
```diff
@@ -347,6 +353,7 @@ StatusOr<HttpResponse> ObjectWriteStreambuf::Flush() {
   // If `result.ok() == false` we never get to this point, so the last response
   // was actually successful. Represent that by a HTTP 200 status code.
   last_response_ = HttpResponse{200, std::move(result).value().payload, {}};
+  last_status_ = Status();
```
Comment (coryan) [inline google/cloud/storage/internal/object_streambuf.cc]: and then we can remove this.

File: google/cloud/storage/object_stream.h [hunk 9]
```diff
@@ -343,6 +343,18 @@ class ObjectWriteStream : public std::basic_ostream<char> {
...
+   * Returns the status of partial errors.
+   *
+   * Application may write multiple times before closing the stream, this
+   * function gives the capability to find out status even before stream
+   * closure.
+   *
+   * This function is different than `metadata()` as calling `metadata()`
+   * before Close() is undefined.
+   */
+  Status const& last_status() const { return buf_->last_status(); }
```
Comment (coryan) [inline google/cloud/storage/object_stream.h]: Probably will need to return by value here.

Comment (manish-qlogic) [reply google/cloud/storage/object_stream.h]: fixed.

File: google/cloud/storage/internal/object_streambuf.cc (hunk 8 above)
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf.cc]: removed.

File: google/cloud/storage/internal/object_streambuf.cc (hunk 7 above)
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf.cc]: done.

File: google/cloud/storage/internal/object_streambuf.h (hunk 1 above)
Comment (manish-qlogic) [reply google/cloud/storage/internal/object_streambuf.h]: done.
