### PR TITLE
Fix flaky integration test(s) for Bigtable.

### LINKED ISSUE #2015: Flaky test: DataIntegrationTest.TableReadMultipleCellsBigValue
One of the tests takes about 10min to run.  It is only enabled against the production environment, so it does not affect our regular builds, but this is clearly too slow.

```
[ RUN      ] DataIntegrationTest.TableReadMultipleCellsBigValue
unknown file: Failure
C++ exception with description "Deadline Exceeded" thrown in the test body.
[  FAILED  ] DataIntegrationTest.TableReadMultipleCellsBigValue (661966 ms)
```

### PR DESCRIPTION
**Pull request by coryan**
We used to create a separate table for each test case in the integration
tests. That makes the test case easier to reason about, but
creating a table is very slow in the production tests, and one can
easily hit the daily or peak quota for Bigtable:

https://cloud.google.com/bigtable/quotas#operation-quotas

In this PR we change the integration tests to share a common table. I
had to normalize the table schema: typically we had column families
named "family{1,2,3}" but sometimes it was "fam{0,1,2,3}". I also
changed the `SetUp()` function to drop all the rows in the table, so at
least the table is clean.

One good thing is that the `TearDown()` function automatically deletes the table,
so we do not need to delete it in each test.

Note that some of the instance admin and table admin tests still create
tables, but those are typically disabled when running against
production.

Apologies for the size of the PR.

This fixes #2015.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2057)

### CODE REVIEW

File: google/cloud/bigtable/testing/table_integration_test.cc [hunk 1]
```diff
@@ -30,6 +31,57 @@ std::string TableTestEnvironment::instance_id_;
...
+}
+
+std::string TableTestEnvironment::RandomTableId() {
+  constexpr int RANDOM_CHARACTERS = 16;
+  return CreateRandomId("table-", RANDOM_CHARACTERS);
+}
+
+std::string TableTestEnvironment::RandomInstanceId() {
+  constexpr int RANDOM_CHARACTERS = 8;
+  return CreateRandomId("it-", RANDOM_CHARACTERS);
```
Comment (devbww) [inline google/cloud/bigtable/testing/table_integration_test.cc]: "it", being short for "instance"?

File: google/cloud/bigtable/testing/table_integration_test.cc [hunk 2]
```diff
@@ -30,6 +31,57 @@ std::string TableTestEnvironment::instance_id_;
...
+
+std::string TableTestEnvironment::CreateRandomId(std::string const& prefix,
+                                                 int count) {
+  return prefix +
+         google::cloud::internal::Sample(
+             generator_, count, "abcdefghijklmnopqrstuvwxyz0123456789");
+}
+
+std::string TableTestEnvironment::RandomTableId() {
+  constexpr int RANDOM_CHARACTERS = 16;
```
Comment (devbww) [inline google/cloud/bigtable/testing/table_integration_test.cc]: What is our naming convention for constants?

File: google/cloud/bigtable/tests/data_integration_test.cc [hunk 3]
```diff
@@ -32,16 +32,11 @@ class DataIntegrationTest : public bigtable::testing::TableIntegrationTest {
   void BulkApply(bigtable::Table& table,
                  std::vector<bigtable::Cell> const& cells);
 
-  std::string const family = "family";
+  /// The column family used in this test.
```
Comment (devbww) [inline google/cloud/bigtable/tests/data_integration_test.cc]: s/family/families/

File: google/cloud/bigtable/tests/data_integration_test.cc [hunk 4]
```diff
@@ -598,41 +561,71 @@ TEST_F(DataIntegrationTest, TableReadMultipleCellsBigValue) {
...
+  auto elapsed_ms = [&start] {
+    using ms = std::chrono::milliseconds;
+    auto now = std::chrono::steady_clock::now();
+    auto elapsed = now - start;
+    start = now;
+    return std::chrono::duration_cast<ms>(elapsed).count();
+  };
+
+  auto table = GetTable();
+  // TODO(#2015) - Capture elapsed time to troubleshoot flakiness.
```
Comment (remyabel) [inline google/cloud/bigtable/tests/data_integration_test.cc]: Are the TODO's still needed here?

File: google/cloud/bigtable/tests/data_integration_test.cc [hunk 5]
```diff
@@ -598,41 +561,71 @@ TEST_F(DataIntegrationTest, TableReadMultipleCellsBigValue) {
...
+  SCOPED_TRACE("CreateTable() " + std::to_string(elapsed_ms()) + "ms");
 
   std::string const row_key = "row-key-1";
-  // cell vector contains 10 cells of 25 MiB
-  auto const MiB = 1024L * 1024L;
-
-  std::string value((25 * MiB), 'a');
+  // cell vector contains 4 cells of 32 MiB each, or 128 MiB (without
+  // considering any overhead). That is much larger that the default gRPC
+  // message size (~4 MiB), and yet much smaller than the configured message
```
Comment (remyabel) [inline google/cloud/bigtable/tests/data_integration_test.cc]: I believe the max was changed to 256MiB. Is this only true for the emulator?

File: google/cloud/bigtable/tests/data_integration_test.cc [hunk 6]
```diff
@@ -598,41 +561,71 @@ TEST_F(DataIntegrationTest, TableReadMultipleCellsBigValue) {
...
+  // size (~256MiB). Therefore, the row would not fit in a message if we failed
+  // to change the default configuration, but it is not so large that it will
+  // fail to work if we miss the overhead estimation.
+  auto const MiB = 1024 * 1024UL;
+  auto const cell_size = 32 * MiB;
+  auto const cell_count = 4;
+  // Smaller rows are not a good test, they would pass with the default setting.
+  auto const min_row_size = 10 * 4 * MiB;
```
Comment (remyabel) [inline google/cloud/bigtable/tests/data_integration_test.cc]: What does `10 * 4` represent here? Or is it just an arbitrary number for testing.

File: google/cloud/bigtable/testing/table_integration_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/bigtable/testing/table_integration_test.cc]: Yup.  I moved this code from elsewhere btw, as I recall the maximum is about 12 , and we want as many as possible for the random portion.

File: google/cloud/bigtable/testing/table_integration_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/bigtable/testing/table_integration_test.cc]: A mess. In principle should be the same as the Google Style Guide.  But we made a mess of them a while back, and the clang-tidy rules need fixing.  I would prefer to tackle that separately these were the constant names I refactored from specific tests.

File: google/cloud/bigtable/tests/data_integration_test.cc (hunk 3 above)
Comment (coryan) [reply google/cloud/bigtable/tests/data_integration_test.cc]: Will do, I need to do taxes now :cry:

File: google/cloud/bigtable/testing/table_integration_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/bigtable/testing/table_integration_test.cc]: So I was wrong, the maximum length is 33 characters (the only place this seems to be documented in is the Web UI, :shrug:). With that much room it makes no sense to abbreviate.

File: google/cloud/bigtable/testing/table_integration_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/bigtable/testing/table_integration_test.cc]: I fixed these to be `kCamelCase`. Apparently our clang-tidy rules are so messed up that anything is accepted here.

File: google/cloud/bigtable/tests/data_integration_test.cc (hunk 3 above)
Comment (coryan) [reply google/cloud/bigtable/tests/data_integration_test.cc]: Fixed.

File: google/cloud/bigtable/tests/data_integration_test.cc (hunk 4 above)
Comment (coryan) [reply google/cloud/bigtable/tests/data_integration_test.cc]: Nope, removed.

File: google/cloud/bigtable/tests/data_integration_test.cc (hunk 5 above)
Comment (coryan) [reply google/cloud/bigtable/tests/data_integration_test.cc]: The default from gRPC is 4MiB.  Our default is 256MiB. That comment refers to the original gRPC default.

File: google/cloud/bigtable/tests/data_integration_test.cc (hunk 6 above)
Comment (coryan) [reply google/cloud/bigtable/tests/data_integration_test.cc]: Added a better explanation.

File: google/cloud/bigtable/tests/admin_integration_test.cc [hunk 7]
```diff
@@ -107,7 +107,9 @@ TEST_F(AdminIntegrationTest, DropRowsByPrefixTest) {
        {column_family2, bigtable::GcRule::MaxNumVersions(10)},
        {column_family3, bigtable::GcRule::MaxNumVersions(10)}},
       {});
-  auto table = CreateTable(table_id, table_config);
+  auto table_meta = table_admin_->CreateTable(table_id, table_config);
```
Comment (dopiera) [inline google/cloud/bigtable/tests/admin_integration_test.cc]: I think this test could use `GetTable()`

File: google/cloud/bigtable/tests/admin_integration_test.cc [hunk 8]
```diff
@@ -148,7 +150,10 @@ TEST_F(AdminIntegrationTest, DropAllRowsTest) {
        {column_family2, bigtable::GcRule::MaxNumVersions(10)},
        {column_family3, bigtable::GcRule::MaxNumVersions(10)}},
       {});
-  auto table = CreateTable(table_id, table_config);
+
+  ASSERT_STATUS_OK(table_admin_->CreateTable(table_id, table_config));
```
Comment (dopiera) [inline google/cloud/bigtable/tests/admin_integration_test.cc]: I think this test could use `GetTable()`.

File: google/cloud/bigtable/tests/admin_async_integration_test.cc [hunk 9]
```diff
@@ -230,7 +230,7 @@ TEST_F(AdminAsyncIntegrationTest, AsyncDropRowsByPrefixTest) {
 
   promise_drop_row.get_future().get();
   auto actual_cells = ReadRows(table, bigtable::Filter::PassAllFilter());
-  EXPECT_STATUS_OK(DeleteTable(table_id));
+  EXPECT_STATUS_OK(table_admin_->DeleteTable(table_id));
```
Comment (dopiera) [inline google/cloud/bigtable/tests/admin_async_integration_test.cc]: I think this test could use `GetTable()`.

File: google/cloud/bigtable/tests/admin_async_integration_test.cc [hunk 10]
```diff
@@ -290,7 +290,7 @@ TEST_F(AdminAsyncIntegrationTest, AsyncDropAllRowsTest) {
   promise_drop_row.get_future().get();
 
   auto actual_cells = ReadRows(table, bigtable::Filter::PassAllFilter());
-  EXPECT_STATUS_OK(DeleteTable(table_id));
+  EXPECT_STATUS_OK(table_admin_->DeleteTable(table_id));
```
Comment (dopiera) [inline google/cloud/bigtable/tests/admin_async_integration_test.cc]: I think this test could use `GetTable()`.

File: google/cloud/bigtable/tests/admin_integration_test.cc [hunk 11]
```diff
@@ -161,11 +166,11 @@ TEST_F(AdminIntegrationTest, DropAllRowsTest) {
...
 
   // Create records
-  CreateCells(*table, created_cells);
+  CreateCells(table, created_cells);
   // Delete all the records from a table
   EXPECT_STATUS_OK(table_admin_->DropAllRows(table_id));
-  auto actual_cells = ReadRows(*table, bigtable::Filter::PassAllFilter());
-  EXPECT_STATUS_OK(DeleteTable(table_id));
+  auto actual_cells = ReadRows(table, bigtable::Filter::PassAllFilter());
+  EXPECT_STATUS_OK(table_admin_->DeleteTable(table_id));
```
Comment (dopiera) [inline google/cloud/bigtable/tests/admin_integration_test.cc]: I think this test could use `GetTable()`.

File: google/cloud/bigtable/tests/snapshot_async_integration_test.cc [hunk 12]
```diff
@@ -153,7 +153,7 @@ TEST_F(SnapshotAsyncIntegrationTest, CreateListGetDeleteSnapshot) {
   EXPECT_FALSE(IsSnapshotPresent(*snapshots_after_delete, snapshot.name()));
 
   // delete table
-  EXPECT_STATUS_OK(DeleteTable(table_id.get()));
+  EXPECT_STATUS_OK(table_admin_->DeleteTable(table_id.get()));
```
Comment (dopiera) [inline google/cloud/bigtable/tests/snapshot_async_integration_test.cc]: I think this test could use `GetTable()`.

File: google/cloud/bigtable/tests/admin_integration_test.cc (hunk 7 above)
Comment (coryan) [reply google/cloud/bigtable/tests/admin_integration_test.cc]: Done.

File: google/cloud/bigtable/tests/admin_integration_test.cc (hunk 8 above)
Comment (coryan) [reply google/cloud/bigtable/tests/admin_integration_test.cc]: Done.

File: google/cloud/bigtable/tests/admin_async_integration_test.cc (hunk 9 above)
Comment (coryan) [reply google/cloud/bigtable/tests/admin_async_integration_test.cc]: Done.

File: google/cloud/bigtable/tests/admin_async_integration_test.cc (hunk 10 above)
Comment (coryan) [reply google/cloud/bigtable/tests/admin_async_integration_test.cc]: Done.

File: google/cloud/bigtable/tests/admin_integration_test.cc (hunk 11 above)
Comment (coryan) [reply google/cloud/bigtable/tests/admin_integration_test.cc]: Done.

File: google/cloud/bigtable/tests/snapshot_async_integration_test.cc (hunk 12 above)
Comment (coryan) [reply google/cloud/bigtable/tests/snapshot_async_integration_test.cc]: Done.

**Comment by coryan** [comment]
Rebased and resolved conflicts.

@remyabel if you have a chance take a look in case I clobbered some of your changes.
