### PR TITLE
fix(spanner): remove session from pool upon "not found" refresh failure

### LINKED ISSUE #4026: remove the Session from the allocation pool if refresh fails with "not found"
We currently use a "send-and-forget" `GetSession()` call to refresh expiring `Session`s.  See `SessionPool::RefreshExpiringSessions()`.

If the `GetSession()` call fails with `kNotFound`, we could remove the session from the allocation pool (although this should never happen if refresh is working correctly).

### PR DESCRIPTION
**Pull request by devbww**
When the "SELECT 1" session-refresh query fails with "Session not found", remove the bad session from the pool, if possible.  Previously we did nothing because (1) it shouldn't happen, and (2) we have other mechanisms in place to deal with bad sessions (which must remain).  But it is better dealt with directly if we can.

Fixes #4026.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/9954)

### CODE REVIEW

File: google/cloud/spanner/internal/session_pool.cc [hunk 1]
```diff
@@ -152,20 +152,43 @@ void SessionPool::RefreshExpiringSessions() {
...
-          // We simply discard the response as handling IsSessionNotFound()
-          // by removing the session from the pool is problematic (and would
-          // not eliminate the possibility of IsSessionNotFound() elsewhere).
-          // The last-use time has already been updated to throttle attempts.
-          // TODO(#4026): Re-evaluate these decisions.
-          (void)result.get();
-        });
+    auto handler =
+        [pool, session_name = refresh.second](
+            future<StatusOr<google::spanner::v1::ResultSet>> result) {
```
Comment (coryan) [inline google/cloud/spanner/internal/session_pool.cc:159]: Optional: use `auto result`

**Review by coryan — APPROVED** [review]
