### PR TITLE
fix(rest): reuse connections in `sql`, `compute`

### LINKED ISSUE #13393: REST layers do not reuse connections with FQDN
See: https://github.com/googleapis/google-cloud-cpp/pull/13357#issuecomment-1867051705

It appears that the REST transport layers stop reusing connections with a FQDN. While there may be some `CURLOPT_*` that saves the day, I did not find it.

We currently append the trailing `.` here, which affects both REST and gRPC generated clients:
https://github.com/googleapis/google-cloud-cpp/blob/f8db9e465333541301d9629651ed3d004101f8f3/google/cloud/internal/populate_common_options.cc#L56

We probably want to remove that line of code for now, and deal with the consequences.

### PR DESCRIPTION
**Pull request by dbolduc**
Fixes #13393 (although we would prefer a solution that both reuses connections and uses fully qualified domain names)

While it is strange to set the `EndpointOption` to be fully qualified, then strip the ending, note that:
- This way we keep using FQDN over gRPC
- We are already manipulating `EndpointOption` in `PopulateRestOptions` after it is set in `PopulateCommonOptions`.

---

If the application supplies us with a custom FQDN via `EndpointOption`, we might leave it as is, and not reuse connections. :shrug:

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13396)

### CODE REVIEW

File: google/cloud/internal/populate_rest_options.cc [hunk 1]
```diff
@@ -35,9 +36,12 @@ Options PopulateRestOptions(Options opts) {
...
   }
   if (opts.has<EndpointOption>()) {
-    std::string endpoint = opts.get<EndpointOption>();
+    auto& endpoint = opts.lookup<EndpointOption>();
+    // Use an unqualified domain name, because we do not seem to reuse
+    // connections with a fully qualified domain name over REST.
+    if (absl::EndsWith(endpoint, ".googleapis.com.")) endpoint.pop_back();
     if (!absl::StartsWithIgnoreCase(endpoint, "http")) {
-      opts.set<EndpointOption>(absl::StrCat("https://", endpoint));
+      endpoint = absl::StrCat("https://", endpoint);
```
Comment (coryan) [inline google/cloud/internal/populate_rest_options.cc:44]: I think there is an open bug regarding the `StartsWithIgnoreCase(..., "http")`, right?  Can you open one if not?

**Review by coryan — APPROVED** [review]

File: google/cloud/internal/populate_rest_options.cc (hunk 1 above)
Comment (dbolduc) [reply google/cloud/internal/populate_rest_options.cc:44]: I did not open a bug. I will just send a follow up PR.

Comment (dbolduc) [reply google/cloud/internal/populate_rest_options.cc:44]: #13397
