### PR TITLE
Send larger chunks is CurlResumableStreambuf.

### LINKED ISSUE #2662: Streaming uploads send very small chunks.
In CurlResumableStreambuf we send chunks of size `max_buffer_size_` (which really should be renamed to `chunk_size_`) even when the application provides much bigger amounts of data per `.write()` call (aka `xsputn()`).

That leads to poor performance and accumulation of data in the buffers, eventually to crashes due to memory exhaustion.

### PR DESCRIPTION
**Pull request by coryan**
The class was sending chunks of size 256KiB (the default configuration parameter),
even when the application provides a multi-megabyte buffer, and then it would save
the buffer to send it later, on the small 256KiB chunks. Sigh...

This version still performs a lot of data copying, but that is a matter for a future
change (there is already an open bug for it).

Fixes #2662.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2668)

### CODE REVIEW

**Comment by coryan** [comment]
Sorry, I found some problems for this code, needs more changes before it is ready for review.

**Comment by coryan** [comment]
Okay, ready for review now.

File: google/cloud/storage/internal/curl_resumable_streambuf_test.cc [hunk 1]
```diff
@@ -0,0 +1,276 @@
...
+namespace {
+
+using ::google::cloud::storage::testing::canonical_errors::PermanentError;
+using ::google::cloud::storage::testing::canonical_errors::TransientError;
+using ::testing::_;
+using ::testing::HasSubstr;
+using ::testing::Invoke;
+using ::testing::Return;
+
+/// @test Verify that uploading a small creates a single chunk.
```
Comment (devbww) [inline google/cloud/storage/internal/curl_resumable_streambuf_test.cc]: "a small \<something\>"?

File: google/cloud/storage/internal/curl_resumable_streambuf_test.cc [hunk 2]
```diff
@@ -0,0 +1,276 @@
...
+      google::cloud::internal::make_unique<NullHashValidator>());
+
+  for (auto const& c : payload) {
+    streambuf.sputc(c);
+  }
+  auto response = streambuf.Close();
+  EXPECT_STATUS_OK(response);
+}
+
+/// @test Verify that a stream flushes when adding one character at a time.
```
Comment (devbww) [inline google/cloud/storage/internal/curl_resumable_streambuf_test.cc]: Same comment as previous test?

Comment (coryan) [reply google/cloud/storage/internal/curl_resumable_streambuf_test.cc]: Fixed.

File: google/cloud/storage/internal/curl_resumable_streambuf_test.cc (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/curl_resumable_streambuf_test.cc]: Fixed.
