### PR TITLE
Do not raise exceptions in ReadObject().

### LINKED ISSUE #2373: Client::ReadObject() still raises errors in some cases.
In most cases `Client::ReadObject()` signals errors by setting the iostream status bits and the `.status()` accessor in the returned `ReadObjectStream`.  But if the error condition is detected before we even create a valid `ReadObjectStreambuf` then the function raises an exception.

That is not the expected behavior.

### PR DESCRIPTION
**Pull request by coryan**
The plan was to return the status in the ReadObjectStream, that was not
working when there were errors (such as authentication problems)
preventing us from even creating a valid ReadObjectStreambuf. The
"solution" proposed here is to create a streambuf that is permanently
set to "this is an error stream, everything is terrible".

I am not sure this is the best fix, and welcome other ideas. It does not
solve all the known problems with error handling in `ReadObject()`, but
I think it is a pre-requisite to solve them. There is a separate bug to track
similar problems on `WriteObject` (#2374), and I think it should have a
similar solution.

This fixes #2373.

---
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/2375)

### CODE REVIEW

File: google/cloud/storage/internal/object_streambuf.h [hunk 1]
```diff
@@ -50,6 +50,33 @@ class ObjectReadStreambuf : public std::basic_streambuf<char> {
   virtual std::multimap<std::string, std::string> const& headers() const = 0;
 };
 
+/**
+ * A read stream in a permanent error status.
```
Comment (devbww) [inline google/cloud/storage/internal/object_streambuf.h]: s/status/state/ perhaps?

File: google/cloud/storage/object_test.cc [hunk 2]
```diff
@@ -391,6 +392,54 @@ TEST_F(ObjectTest, PatchObjectPermanentFailure) {
...
+
+  Status status =
+      client.ReadObject("test-bucket-name", "test-object-name").status();
+  EXPECT_EQ(TransientError().code(), status.code());
+  EXPECT_THAT(status.message(), HasSubstr("Retry policy exhausted"));
+  EXPECT_THAT(status.message(), HasSubstr("ReadObject"));
+}
+
+TEST_F(ObjectTest, ReadObjectPermanentFailure) {
+  // We cannot use google::cloud::storage::testing::TooManyFailuresStatusTest,
```
Comment (devbww) [inline google/cloud/storage/object_test.cc]: s/TooManyFailuresStatusTest/PermanentFailureStatusTest/?

File: google/cloud/storage/internal/object_streambuf.h (hunk 1 above)
Comment (coryan) [reply google/cloud/storage/internal/object_streambuf.h]: Fixed, much better.

File: google/cloud/storage/object_test.cc (hunk 2 above)
Comment (coryan) [reply google/cloud/storage/object_test.cc]: Fixed. Thanks!

**Comment by coryan** [comment]
PTAL. I added a unit test because I needed a fix of code coverage improvements.
