### PR TITLE
fix(generator): also scan parameter comments for references

### LINKED ISSUE #11885: Add links in method_signature documentation
Sometimes the generator creates overloads based on `google.api.method_signature`.  For example, this RPC would create two overloads:

https://github.com/googleapis/googleapis/blob/854b6a9e7f122ca6b13c92327ad2c36b2fc1e729/google/cloud/kms/v1/service.proto#L97-L101

The generator creates the overload with a `name` field:

https://github.com/googleapis/google-cloud-cpp/blob/f3d6cf5e29aac62eb1a31b130c4b630d59c51ca7/google/cloud/kms/v1/key_management_client.h#L504-L505

The documentation for these overloads pulls the documentation of the fields from the protos, so this:

https://github.com/googleapis/googleapis/blob/854b6a9e7f122ca6b13c92327ad2c36b2fc1e729/google/cloud/kms/v1/service.proto#L624-L625

Becomes this:

https://github.com/googleapis/google-cloud-cpp/blob/f3d6cf5e29aac62eb1a31b130c4b630d59c51ca7/google/cloud/kms/v1/key_management_client.h#L478-L480

The generated code extracts links used in the proto message documentation. But it misses the links in the `GetCryptoKeyrequest.name` field documentation:

https://github.com/googleapis/google-cloud-cpp/blob/f3d6cf5e29aac62eb1a31b130c4b630d59c51ca7/google/cloud/kms/v1/key_management_client.h#L491-L501

This results in broken links in the generated documentation, e.g.:

https://cloud.google.com/cpp/docs/reference/kms/latest/classgoogle_1_1cloud_1_1kms__v1_1_1KeyManagementServiceClient#classgoogle_1_1cloud_1_1kms__v1_1_1KeyManagementServiceClient_1a4241a8b6f26091fc32c408ea40136fb4

### PR DESCRIPTION
**Pull request by devbww**
Fixes #11885.

- - -
This change is [Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/13248)

### CODE REVIEW

File: generator/internal/format_method_comments.cc [hunk 1]
```diff
@@ -162,8 +172,11 @@ std::string FormatMethodComments(
 
   auto const return_comment_string = ReturnCommentString(method);
 
-  auto references = ResolveCommentReferences(
-      method_source_location.leading_comments, *method.file()->pool());
+  auto references =
```
Comment (coryan) [inline generator/internal/format_method_comments.cc:175]: Neat!

File: google/cloud/aiplatform/v1/dataset_client.h [hunk 2]
```diff
@@ -242,6 +242,7 @@ class DatasetServiceClient {
   /// [`Status`]: @ref google::cloud::Status
   /// [google.cloud.aiplatform.v1.Dataset]: @googleapis_reference_link{google/cloud/aiplatform/v1/dataset.proto#L36}
   /// [google.cloud.aiplatform.v1.UpdateDatasetRequest]: @googleapis_reference_link{google/cloud/aiplatform/v1/dataset_service.proto#L280}
+  /// [google.protobuf.FieldMask]: @googleapis_reference_link{google/protobuf/field_mask.proto#L242}
```
Comment (coryan) [inline google/cloud/aiplatform/v1/dataset_client.h:245]: FYI: I think `@googleapis_reference_link{}` does not work for well-known protos.  It will expand to:

https://github.com/googleapis/google-cloud-cpp/blob/6203e23223c5093aee647284fbbc08744a27b02d/cmake/GoogleapisConfig.cmake#L36

And the file does not exist in the `googleapis/googleapis` repository:

https://github.com/googleapis/googleapis/tree/master/google/protobuf

In a separate PR we should make the `ResolveCommentReferences()` function do something clever for well-known protos.

**Review by coryan — APPROVED** [review]

**Comment by dbolduc** [comment]
Is this unit-testable?

**Comment by devbww** [comment]
> Is this unit-testable?

Enabled coverage in an existing test by correcting the name of the (copied) `LogEntry` message.  Now golden/v1/golden_kitchen_sink_client.h will have a link for a reference originating in a method-signature parameter comment.

**Comment by dbolduc** [comment]
If we revert the generator changes, nothing would fail. We typically run generate-libraries and commit the result. Just saying.

**Comment by devbww** [comment]
> If we revert the generator changes, nothing would fail.

Wouldn't the golden tests fail?

> We typically run generate-libraries and commit the result. Just saying.

Acknowledged.  But that is an indictment of the _"run generate-libraries and commit the result"_ process.  Any changes committed to golden files should be justified.
